local _, internal = ...

local function appendData(extra_data)
	for _, item in ipairs(extra_data) do
		tinsert(internal.data.items, item)
	end
end
internal.appendData = appendData

internal.data = {
	categories = {
		[0] = "Miscellaneous",
		[171] = "Alchemy",
		[164] = "Blacksmithing",
		[185] = "Cooking",
		[333] = "Enchanting",
		[202] = "Engineering",
		[129] = "First Aid",
		[182] = "Herbalism",
		[773] = "Inscription",
		[755] = "Jewelcrafting",
		[165] = "Leatherworking",
		[186] = "Mining",
		[393] = "Skinning",
		[197] = "Tailoring",
	},
	items = {},
	--[[
	old_items = {
		{
			id = 765,
			name = "Silverleaf",
			icon = "Interface\\Icons\\INV_Misc_Herb_10",
			categories = { 171, 182 },
		},
		{
			id = 785,
			name = "Mageroyal",
			icon = "Interface\\Icons\\INV_Jewelry_Talisman_03",
			categories = { 171, 185, 773, 182 },
		},
		{
			id = 1288,
			name = "Large Venom Sac",
			icon = "Interface\\Icons\\INV_Misc_Organ_01",
			categories = { 171, 129 },
		},
		{
			id = 2447,
			name = "Peacebloom",
			icon = "Interface\\Icons\\INV_Misc_Flower_02",
			categories = { 171, 182 },
		},
		{
			id = 2449,
			name = "Earthroot",
			icon = "Interface\\Icons\\INV_Misc_Herb_07",
			categories = { 171, 182 },
		},
		{
			id = 2450,
			name = "Briarthorn",
			icon = "Interface\\Icons\\INV_Misc_Root_01",
			categories = { 171, 182 },
		},
		{
			id = 2452,
			name = "Swiftthistle",
			icon = "Interface\\Icons\\INV_Misc_Herb_04",
			categories = { 171, 185, 182 },
		},
		{
			id = 2453,
			name = "Bruiseweed",
			icon = "Interface\\Icons\\INV_Misc_Herb_01",
			categories = { 171, 182 },
		},
		{
			id = 3164,
			name = "Discolored Worg Heart",
			icon = "Interface\\Icons\\INV_Misc_Organ_02",
			categories = { 171 },
		},
		{
			id = 3355,
			name = "Wild Steelbloom",
			icon = "Interface\\Icons\\INV_Misc_Flower_01",
			categories = { 171, 182 },
		},
		{
			id = 3356,
			name = "Kingsblood",
			icon = "Interface\\Icons\\INV_Misc_Herb_03",
			categories = { 171, 165, 333, 182 },
		},
		{
			id = 3357,
			name = "Liferoot",
			icon = "Interface\\Icons\\INV_Misc_Root_02",
			categories = { 171, 182 },
		},
		{
			id = 3358,
			name = "Khadgar's Whisker",
			icon = "Interface\\Icons\\INV_Misc_Herb_08",
			categories = { 171, 182 },
		},
		{
			id = 3369,
			name = "Grave Moss",
			icon = "Interface\\Icons\\INV_Misc_Dust_02",
			categories = { 171, 182 },
		},
		{
			id = 3371,
			name = "Empty Vial",
			icon = "Interface\\Icons\\INV_Drink_06",
			categories = { 171, 333 },
		},
		{
			id = 3372,
			name = "Leaded Vial",
			icon = "Interface\\Icons\\INV_Alchemy_LeadedVial",
			categories = { 171, 333 },
		},
		{
			id = 3575,
			name = "Iron Bar",
			icon = "Interface\\Icons\\INV_Ingot_Iron",
			categories = { 164, 186, 202, 171, 755 },
		},
		{
			id = 3818,
			name = "Fadeleaf",
			icon = "Interface\\Icons\\INV_Misc_Herb_12",
			categories = { 171, 182 },
		},
		{
			id = 3819,
			name = "Wintersbite",
			icon = "Interface\\Icons\\INV_Misc_Flower_03",
			categories = { 171, 333, 182 },
		},
		{
			id = 3820,
			name = "Stranglekelp",
			icon = "Interface\\Icons\\INV_Misc_Herb_11",
			categories = { 171, 182 },
		},
		{
			id = 3821,
			name = "Goldthorn",
			icon = "Interface\\Icons\\INV_Misc_Herb_15",
			categories = { 171, 185, 182 },
		},
		{
			id = 3858,
			name = "Mithril Ore",
			icon = "Interface\\Icons\\INV_Ore_Mithril_02",
			categories = { 171, 186 },
		},
		{
			id = 3860,
			name = "Mithril Bar",
			icon = "Interface\\Icons\\INV_Ingot_06",
			categories = { 164, 171, 202, 755 },
		},
		{
			id = 4342,
			name = "Purple Dye",
			icon = "Interface\\Icons\\INV_Potion_02",
			categories = { 197, 171, 165, 202 },
		},
		{
			id = 4402,
			name = "Small Flame Sac",
			icon = "Interface\\Icons\\INV_Misc_Organ_06",
			categories = { 202, 171, 185 },
		},
		{
			id = 4625,
			name = "Firebloom",
			icon = "Interface\\Icons\\INV_Misc_Herb_19",
			categories = { 171, 333, 197, 182 },
		},
		{
			id = 5635,
			name = "Sharp Claw",
			icon = "Interface\\Icons\\INV_Misc_MonsterClaw_03",
			categories = { 171, 164 },
		},
		{
			id = 5637,
			name = "Large Fang",
			icon = "Interface\\Icons\\INV_Misc_Bone_08",
			categories = { 165, 171, 164, 333, 755 },
		},
		{
			id = 6358,
			name = "Oily Blackmouth",
			icon = "Interface\\Icons\\INV_Misc_MonsterHead_04",
			categories = { 171 },
		},
		{
			id = 6359,
			name = "Firefin Snapper",
			icon = "Interface\\Icons\\INV_Misc_MonsterHead_01",
			categories = { 171 },
		},
		{
			id = 6370,
			name = "Blackmouth Oil",
			icon = "Interface\\Icons\\INV_Drink_12",
			categories = { 171, 333 },
		},
		{
			id = 6371,
			name = "Fire Oil",
			icon = "Interface\\Icons\\INV_Potion_38",
			categories = { 171, 333, 197 },
		},
		{
			id = 6522,
			name = "Deviate Fish",
			icon = "Interface\\Icons\\INV_Misc_MonsterHead_01",
			categories = { 185, 171 },
		},
		{
			id = 7067,
			name = "Elemental Earth",
			icon = "Interface\\Icons\\INV_Ore_Iron_01",
			categories = { 197, 165, 164, 171, 202, 333, 755 },
		},
		{
			id = 7068,
			name = "Elemental Fire",
			icon = "Interface\\Icons\\Spell_Fire_Fire",
			categories = { 197, 202, 333, 164, 171 },
		},
		{
			id = 7069,
			name = "Elemental Air",
			icon = "Interface\\Icons\\Spell_Nature_Tranquility",
			categories = { 197, 171, 164, 202 },
		},
		{
			id = 7070,
			name = "Elemental Water",
			icon = "Interface\\Icons\\INV_Potion_03",
			categories = { 197, 165, 171, 164, 755 },
		},
		{
			id = 7076,
			name = "Essence of Earth",
			icon = "Interface\\Icons\\Spell_Nature_StrengthOfEarthTotem02",
			categories = { 164, 171, 197, 165, 202, 333, 755, 186 },
		},
		{
			id = 7077,
			name = "Heart of Fire",
			icon = "Interface\\Icons\\Spell_Fire_LavaSpawn",
			categories = { 164, 165, 197, 202, 333, 171, 755 },
		},
		{
			id = 7078,
			name = "Essence of Fire",
			icon = "Interface\\Icons\\Spell_Fire_Volcano",
			categories = { 333, 164, 171, 197, 165, 202, 755 },
		},
		{
			id = 7080,
			name = "Essence of Water",
			icon = "Interface\\Icons\\Spell_Nature_Acid_01",
			categories = { 164, 171, 197, 165, 333, 202 },
		},
		{
			id = 7082,
			name = "Essence of Air",
			icon = "Interface\\Icons\\Spell_Nature_EarthBind",
			categories = { 171, 197, 165, 333, 202, 755 },
		},
		{
			id = 7972,
			name = "Ichor of Undeath",
			icon = "Interface\\Icons\\INV_Misc_Slime_01",
			categories = { 164, 202, 333, 171, 197 },
		},
		{
			id = 8153,
			name = "Wildvine",
			icon = "Interface\\Icons\\INV_Misc_Herb_03",
			categories = { 165, 171, 197, 202, 333, 164, 182 },
		},
		{
			id = 8831,
			name = "Purple Lotus",
			icon = "Interface\\Icons\\INV_Misc_Herb_17",
			categories = { 171, 333, 197, 182 },
		},
		{
			id = 8836,
			name = "Arthas' Tears",
			icon = "Interface\\Icons\\INV_Misc_Herb_13",
			categories = { 171, 182 },
		},
		{
			id = 8838,
			name = "Sungrass",
			icon = "Interface\\Icons\\INV_Misc_Herb_18",
			categories = { 171, 333, 182 },
		},
		{
			id = 8839,
			name = "Blindweed",
			icon = "Interface\\Icons\\INV_Misc_Herb_14",
			categories = { 171, 182 },
		},
		{
			id = 8845,
			name = "Ghost Mushroom",
			icon = "Interface\\Icons\\INV_Mushroom_08",
			categories = { 171, 182 },
		},
		{
			id = 8846,
			name = "Gromsblood",
			icon = "Interface\\Icons\\INV_Misc_Herb_16",
			categories = { 171, 182 },
		},
		{
			id = 8925,
			name = "Crystal Vial",
			icon = "Interface\\Icons\\INV_Alchemy_CrystalVial",
			categories = { 171, 333 },
		},
		{
			id = 9260,
			name = "Volatile Rum",
			icon = "Interface\\Icons\\INV_Drink_01",
			categories = { 171 },
		},
		{
			id = 9262,
			name = "Black Vitriol",
			icon = "Interface\\Icons\\INV_Misc_Gem_Sapphire_03",
			categories = { 171, 186 },
		},
		{
			id = 10286,
			name = "Heart of the Wild",
			icon = "Interface\\Icons\\INV_Misc_Herb_08",
			categories = { 197, 202, 171, 755 },
		},
		{
			id = 10620,
			name = "Thorium Ore",
			icon = "Interface\\Icons\\INV_Ore_Thorium_02",
			categories = { 186, 171 },
		},
		{
			id = 11176,
			name = "Dream Dust",
			icon = "Interface\\Icons\\INV_Enchant_DustDream",
			categories = { 333, 171, 197, 186 },
		},
		{
			id = 12359,
			name = "Thorium Bar",
			icon = "Interface\\Icons\\INV_Ingot_07",
			categories = { 164, 333, 171, 202, 755, 186 },
		},
		{
			id = 12363,
			name = "Arcane Crystal",
			icon = "Interface\\Icons\\INV_Misc_Gem_Topaz_01",
			categories = { 171, 755, 333, 186 },
		},
		{
			id = 12803,
			name = "Living Essence",
			icon = "Interface\\Icons\\Spell_Nature_AbolishMagic",
			categories = { 164, 171, 165, 202, 333, 197, 755 },
		},
		{
			id = 12804,
			name = "Powerful Mojo",
			icon = "Interface\\Icons\\Spell_Nature_AstralRecalGroup",
			categories = { 164, 165, 197, 171, 202, 755 },
		},
		{
			id = 12808,
			name = "Essence of Undeath",
			icon = "Interface\\Icons\\Spell_Shadow_ShadeTrueSight",
			categories = { 202, 164, 171, 197, 333, 755, 185 },
		},
		{
			id = 12938,
			name = "Blood of Heroes",
			icon = "Interface\\Icons\\INV_Potion_33",
			categories = { 171, 755 },
		},
		{
			id = 13422,
			name = "Stonescale Eel",
			icon = "Interface\\Icons\\INV_Misc_Fish_11",
			categories = { 171 },
		},
		{
			id = 13423,
			name = "Stonescale Oil",
			icon = "Interface\\Icons\\INV_Potion_68",
			categories = { 171 },
		},
		{
			id = 13463,
			name = "Dreamfoil",
			icon = "Interface\\Icons\\INV_Misc_Herb_DreamFoil",
			categories = { 171, 182 },
		},
		{
			id = 13464,
			name = "Golden Sansam",
			icon = "Interface\\Icons\\INV_Misc_Herb_SansamRoot",
			categories = { 171, 182 },
		},
		{
			id = 13465,
			name = "Mountain Silversage",
			icon = "Interface\\Icons\\INV_Misc_Herb_MountainSilverSage",
			categories = { 171, 182 },
		},
		{
			id = 13466,
			name = "Plaguebloom",
			icon = "Interface\\Icons\\INV_Misc_Herb_PlagueBloom",
			categories = { 171, 182 },
		},
		{
			id = 13467,
			name = "Icecap",
			icon = "Interface\\Icons\\INV_Misc_Herb_IceCap",
			categories = { 171, 333, 202, 182 },
		},
		{
			id = 13468,
			name = "Black Lotus",
			icon = "Interface\\Icons\\INV_Misc_Herb_BlackLotus",
			categories = { 171, 197, 182 },
		},
		{
			id = 18256,
			name = "Imbued Vial",
			icon = "Interface\\Icons\\INV_Alchemy_ImbuedVial",
			categories = { 171, 333 },
		},
		{
			id = 19943,
			name = "Massive Mojo",
			icon = "Interface\\Icons\\Spell_Nature_Strength",
			categories = { 171 },
		},
		{
			id = 21884,
			name = "Primal Fire",
			icon = "Interface\\Icons\\INV_Elemental_Primal_Fire",
			categories = { 197, 333, 171, 164, 202, 755, 165, 186 },
		},
		{
			id = 21885,
			name = "Primal Water",
			icon = "Interface\\Icons\\INV_Elemental_Primal_Water",
			categories = { 197, 333, 171, 164, 202, 755, 165 },
		},
		{
			id = 21886,
			name = "Primal Life",
			icon = "Interface\\Icons\\INV_Elemental_Primal_Life",
			categories = { 333, 197, 171, 164, 202, 755, 165, 773 },
		},
		{
			id = 21929,
			name = "Flame Spessarite",
			icon = "Interface\\Icons\\INV_Misc_Gem_FlameSpessarite_03",
			categories = { 755, 202, 171, 186 },
		},
		{
			id = 22451,
			name = "Primal Air",
			icon = "Interface\\Icons\\INV_Elemental_Primal_Air",
			categories = { 333, 171, 164, 202, 197, 165, 755 },
		},
		{
			id = 22452,
			name = "Primal Earth",
			icon = "Interface\\Icons\\INV_Elemental_Primal_Earth",
			categories = { 333, 171, 164, 202, 755, 197, 165, 186 },
		},
		{
			id = 22456,
			name = "Primal Shadow",
			icon = "Interface\\Icons\\INV_Elemental_Primal_Shadow",
			categories = { 333, 171, 164, 202, 755, 197, 165 },
		},
		{
			id = 22457,
			name = "Primal Mana",
			icon = "Interface\\Icons\\INV_Elemental_Primal_Mana",
			categories = { 197, 171, 164, 202, 755, 165, 333 },
		},
		{
			id = 22573,
			name = "Mote of Earth",
			icon = "Interface\\Icons\\INV_Elemental_Mote_Earth01",
			categories = { 333, 171, 164, 202, 186 },
		},
		{
			id = 22574,
			name = "Mote of Fire",
			icon = "Interface\\Icons\\INV_Elemental_Mote_Fire01",
			categories = { 333, 171, 202, 186 },
		},
		{
			id = 22578,
			name = "Mote of Water",
			icon = "Interface\\Icons\\INV_Elemental_Mote_Water01",
			categories = { 333, 171, 755 },
		},
		{
			id = 22785,
			name = "Felweed",
			icon = "Interface\\Icons\\INV_Misc_Herb_Felweed",
			categories = { 171, 182 },
		},
		{
			id = 22786,
			name = "Dreaming Glory",
			icon = "Interface\\Icons\\INV_Misc_Herb_Dreamingglory",
			categories = { 171, 182 },
		},
		{
			id = 22787,
			name = "Ragveil",
			icon = "Interface\\Icons\\INV_Misc_Herb_Ragveil",
			categories = { 171, 182 },
		},
		{
			id = 22789,
			name = "Terocone",
			icon = "Interface\\Icons\\INV_Misc_Herb_Terrocone",
			categories = { 171, 182 },
		},
		{
			id = 22790,
			name = "Ancient Lichen",
			icon = "Interface\\Icons\\INV_MISC_HERB_ANCIENTLICHEN",
			categories = { 171, 182 },
		},
		{
			id = 22791,
			name = "Netherbloom",
			icon = "Interface\\Icons\\INV_Misc_Herb_Netherbloom",
			categories = { 333, 171, 182 },
		},
		{
			id = 22792,
			name = "Nightmare Vine",
			icon = "Interface\\Icons\\INV_Misc_Herb_Nightmarevine",
			categories = { 333, 171, 182 },
		},
		{
			id = 22793,
			name = "Mana Thistle",
			icon = "Interface\\Icons\\INV_Misc_Herb_Manathistle",
			categories = { 171, 182 },
		},
		{
			id = 22794,
			name = "Fel Lotus",
			icon = "Interface\\Icons\\INV_Misc_Herb_FelLotus",
			categories = { 171, 333, 197, 182 },
		},
		{
			id = 23077,
			name = "Blood Garnet",
			icon = "Interface\\Icons\\INV_Misc_Gem_BloodGem_03",
			categories = { 755, 202, 171, 186 },
		},
		{
			id = 23079,
			name = "Deep Peridot",
			icon = "Interface\\Icons\\INV_Misc_Gem_DeepPeridot_03",
			categories = { 755, 202, 171, 186 },
		},
		{
			id = 23107,
			name = "Shadow Draenite",
			icon = "Interface\\Icons\\INV_Misc_Gem_EbonDraenite_03",
			categories = { 755, 171, 186 },
		},
		{
			id = 23112,
			name = "Golden Draenite",
			icon = "Interface\\Icons\\INV_Misc_Gem_GoldenDraenite_03",
			categories = { 755, 202, 171, 197, 186 },
		},
		{
			id = 23117,
			name = "Azure Moonstone",
			icon = "Interface\\Icons\\INV_Misc_Gem_AzureDraenite_03",
			categories = { 755, 171, 186 },
		},
		{
			id = 23571,
			name = "Primal Might",
			icon = "Interface\\Icons\\Spell_Nature_LightningOverload",
			categories = { 171, 333, 164, 197, 165, 202, 755 },
		},
		{
			id = 23782,
			name = "Fel Iron Casing",
			icon = "Interface\\Icons\\INV_Gizmo_FelIronCasing",
			categories = { 202, 171 },
		},
		{
			id = 25867,
			name = "Earthstorm Diamond",
			icon = "Interface\\Icons\\INV_Misc_Gem_Diamond_04",
			categories = { 171, 755 },
		},
		{
			id = 25868,
			name = "Skyfire Diamond",
			icon = "Interface\\Icons\\INV_Misc_Gem_Diamond_05",
			categories = { 171, 755 },
		},
		{
			id = 30183,
			name = "Nether Vortex",
			icon = "Interface\\Icons\\INV_Elemental_Mote_Nether",
			categories = { 164, 197, 165, 171 },
		},
		{
			id = 35622,
			name = "Eternal Water",
			icon = "Interface\\Icons\\INV_Elemental_Eternal_Water",
			categories = { 333, 171, 164, 197, 755, 202, 165 },
		},
		{
			id = 35623,
			name = "Eternal Air",
			icon = "Interface\\Icons\\INV_Elemental_Eternal_Air",
			categories = { 333, 171, 165, 164, 755, 202 },
		},
		{
			id = 35624,
			name = "Eternal Earth",
			icon = "Interface\\Icons\\INV_Elemental_Eternal_Earth",
			categories = { 333, 171, 186, 164, 755, 202, 165, 197 },
		},
		{
			id = 35625,
			name = "Eternal Life",
			icon = "Interface\\Icons\\INV_Elemental_Eternal_Life",
			categories = { 333, 171, 197, 755, 202, 773, 165, 164 },
		},
		{
			id = 35627,
			name = "Eternal Shadow",
			icon = "Interface\\Icons\\INV_Elemental_Eternal_Shadow",
			categories = { 333, 171, 186, 164, 197, 755, 202, 165, 773 },
		},
		{
			id = 36860,
			name = "Eternal Fire",
			icon = "Interface\\Icons\\INV_Elemental_Eternal_Fire",
			categories = { 333, 171, 186, 164, 197, 755, 202, 165 },
		},
		{
			id = 36901,
			name = "Goldclover",
			icon = "Interface\\Icons\\INV_Misc_Herb_GoldClover",
			categories = { 171, 182 },
		},
		{
			id = 36903,
			name = "Adder's Tongue",
			icon = "Interface\\Icons\\INV_Misc_Herb_EvergreenMoss",
			categories = { 171, 182 },
		},
		{
			id = 36904,
			name = "Tiger Lily",
			icon = "Interface\\Icons\\INV_Misc_Herb_Tigerlily",
			categories = { 171, 182 },
		},
		{
			id = 36905,
			name = "Lichbloom",
			icon = "Interface\\Icons\\INV_Misc_Herb_Whispervine",
			categories = { 171, 182 },
		},
		{
			id = 36906,
			name = "Icethorn",
			icon = "Interface\\Icons\\INV_Misc_Herb_IceThorn",
			categories = { 171, 182 },
		},
		{
			id = 36907,
			name = "Talandra's Rose",
			icon = "Interface\\Icons\\INV_Misc_Herb_TalandrasRose",
			categories = { 171, 182 },
		},
		{
			id = 36908,
			name = "Frost Lotus",
			icon = "Interface\\Icons\\INV_Misc_Herb_FrostLotus",
			categories = { 171, 197, 182 },
		},
		{
			id = 36913,
			name = "Saronite Bar",
			icon = "Interface\\Icons\\INV_Ingot_Yoggthorite",
			categories = { 202, 164, 171 },
		},
		{
			id = 36917,
			name = "Bloodstone",
			icon = "Interface\\Icons\\INV_Jewelcrafting_Gem_12",
			categories = { 755, 171, 186 },
		},
		{
			id = 36918,
			name = "Scarlet Ruby",
			icon = "Interface\\Icons\\INV_Jewelcrafting_Gem_04",
			categories = { 755, 202, 333, 171, 186 },
		},
		{
			id = 36921,
			name = "Autumn's Glow",
			icon = "Interface\\Icons\\INV_Jewelcrafting_Gem_03",
			categories = { 755, 202, 171, 186 },
		},
		{
			id = 36923,
			name = "Chalcedony",
			icon = "Interface\\Icons\\INV_Jewelcrafting_Gem_10",
			categories = { 755, 171, 186 },
		},
		{
			id = 36924,
			name = "Sky Sapphire",
			icon = "Interface\\Icons\\INV_Jewelcrafting_Gem_05",
			categories = { 755, 202, 171, 186 },
		},
		{
			id = 36927,
			name = "Twilight Opal",
			icon = "Interface\\Icons\\INV_Jewelcrafting_Gem_06",
			categories = { 755, 202, 171, 186 },
		},
		{
			id = 36929,
			name = "Huge Citrine",
			icon = "Interface\\Icons\\INV_Jewelcrafting_Gem_09",
			categories = { 755, 171, 186 },
		},
		{
			id = 36930,
			name = "Monarch Topaz",
			icon = "Interface\\Icons\\INV_Jewelcrafting_Gem_02",
			categories = { 755, 202, 197, 171, 186 },
		},
		{
			id = 36932,
			name = "Dark Jade",
			icon = "Interface\\Icons\\INV_Jewelcrafting_Gem_07",
			categories = { 755, 171, 186 },
		},
		{
			id = 36933,
			name = "Forest Emerald",
			icon = "Interface\\Icons\\INV_Jewelcrafting_Gem_01",
			categories = { 755, 202, 171, 186 },
		},
		{
			id = 37701,
			name = "Crystallized Earth",
			icon = "Interface\\Icons\\INV_Elemental_Crystal_Earth",
			categories = { 171, 164, 755, 202, 197, 186 },
		},
		{
			id = 37702,
			name = "Crystallized Fire",
			icon = "Interface\\Icons\\INV_Elemental_Crystal_Fire",
			categories = { 171, 164, 197, 202, 186 },
		},
		{
			id = 37703,
			name = "Crystallized Shadow",
			icon = "Interface\\Icons\\INV_Elemental_Crystal_Shadow",
			categories = { 171, 164, 197, 165, 202, 186 },
		},
		{
			id = 37704,
			name = "Crystallized Life",
			icon = "Interface\\Icons\\INV_Elemental_Crystal_Life",
			categories = { 171, 197, 182 },
		},
		{
			id = 37705,
			name = "Crystallized Water",
			icon = "Interface\\Icons\\INV_Elemental_Crystal_Water",
			categories = { 202, 171, 164, 165, 333, 186 },
		},
		{
			id = 37921,
			name = "Deadnettle",
			icon = "Interface\\Icons\\INV_Misc_Herb_ConstrictorGrass",
			categories = { 171, 182 },
		},
		{
			id = 39970,
			name = "Fire Leaf",
			icon = "Interface\\Icons\\INV_Misc_Herb_11a",
			categories = { 171, 182 },
		},
		{
			id = 40195,
			name = "Pygmy Oil",
			icon = "Interface\\Icons\\INV_Potion_07",
			categories = { 171 },
		},
		{
			id = 40199,
			name = "Pygmy Suckerfish",
			icon = "Interface\\Icons\\INV_Misc_Fish_55",
			categories = { 171 },
		},
		{
			id = 40411,
			name = "Enchanted Vial",
			icon = "Interface\\Icons\\INV_Alchemy_EnchantedVial",
			categories = { 171 },
		},
		{
			id = 41814,
			name = "Glassfin Minnow",
			icon = "Interface\\Icons\\INV_Misc_Fish_69",
			categories = { 171 },
		},
		{
			id = 44958,
			name = "Ethereal Oil",
			icon = "Interface\\Icons\\INV_Drink_11",
			categories = { 171, 333 },
		},
		{
			id = 774,
			name = "Malachite",
			icon = "Interface\\Icons\\INV_Misc_Gem_Emerald_03",
			categories = { 164, 202, 755, 186 },
		},
		{
			id = 818,
			name = "Tigerseye",
			icon = "Interface\\Icons\\INV_Misc_Gem_Opal_03",
			categories = { 164, 202, 755, 186 },
		},
		{
			id = 1206,
			name = "Moss Agate",
			icon = "Interface\\Icons\\INV_Misc_Gem_Emerald_02",
			categories = { 164, 202, 165, 755, 186 },
		},
		{
			id = 1210,
			name = "Shadowgem",
			icon = "Interface\\Icons\\INV_Misc_Gem_Amethyst_01",
			categories = { 164, 202, 755, 186 },
		},
		{
			id = 1529,
			name = "Jade",
			icon = "Interface\\Icons\\INV_Misc_Gem_Stone_01",
			categories = { 164, 165, 202, 197, 755, 186 },
		},
		{
			id = 1705,
			name = "Lesser Moonstone",
			icon = "Interface\\Icons\\INV_Misc_Gem_Crystal_01",
			categories = { 164, 202, 755, 186 },
		},
		{
			id = 2318,
			name = "Light Leather",
			icon = "Interface\\Icons\\INV_Misc_LeatherScrap_03",
			categories = { 165, 164, 197, 202, 393 },
		},
		{
			id = 2319,
			name = "Medium Leather",
			icon = "Interface\\Icons\\INV_Misc_LeatherScrap_05",
			categories = { 165, 164, 197, 202, 393 },
		},
		{
			id = 2321,
			name = "Fine Thread",
			icon = "Interface\\Icons\\INV_Fabric_Wool_02",
			categories = { 165, 164, 197 },
		},
		{
			id = 2589,
			name = "Linen Cloth",
			icon = "Interface\\Icons\\INV_Fabric_Linen_01",
			categories = { 164, 129, 197, 202, 186 },
		},
		{
			id = 2592,
			name = "Wool Cloth",
			icon = "Interface\\Icons\\INV_Fabric_Wool_01",
			categories = { 164, 129, 197, 202, 393 },
		},
		{
			id = 2605,
			name = "Green Dye",
			icon = "Interface\\Icons\\INV_Potion_12",
			categories = { 164, 165, 197, 202 },
		},
		{
			id = 2835,
			name = "Rough Stone",
			icon = "Interface\\Icons\\INV_Stone_06",
			categories = { 164, 202, 755, 186 },
		},
		{
			id = 2836,
			name = "Coarse Stone",
			icon = "Interface\\Icons\\INV_Stone_09",
			categories = { 164, 202, 755, 186 },
		},
		{
			id = 2838,
			name = "Heavy Stone",
			icon = "Interface\\Icons\\INV_Stone_12",
			categories = { 164, 202, 755, 186 },
		},
		{
			id = 2840,
			name = "Copper Bar",
			icon = "Interface\\Icons\\INV_Ingot_02",
			categories = { 186, 164, 202, 755, 165 },
		},
		{
			id = 2841,
			name = "Bronze Bar",
			icon = "Interface\\Icons\\INV_Ingot_Bronze",
			categories = { 164, 202, 755 },
		},
		{
			id = 2842,
			name = "Silver Bar",
			icon = "Interface\\Icons\\INV_Ingot_01",
			categories = { 164, 202, 755 },
		},
		{
			id = 2880,
			name = "Weak Flux",
			icon = "Interface\\Icons\\INV_Misc_Ammo_Gunpowder_02",
			categories = { 164, 202 },
		},
		{
			id = 3466,
			name = "Strong Flux",
			icon = "Interface\\Icons\\INV_Misc_Ammo_Gunpowder_01",
			categories = { 164 },
		},
		{
			id = 3470,
			name = "Rough Grinding Stone",
			icon = "Interface\\Icons\\INV_Stone_GrindingStone_01",
			categories = { 164 },
		},
		{
			id = 3478,
			name = "Coarse Grinding Stone",
			icon = "Interface\\Icons\\INV_Stone_GrindingStone_02",
			categories = { 164 },
		},
		{
			id = 3486,
			name = "Heavy Grinding Stone",
			icon = "Interface\\Icons\\INV_Stone_GrindingStone_03",
			categories = { 164 },
		},
		{
			id = 3577,
			name = "Gold Bar",
			icon = "Interface\\Icons\\INV_Ingot_03",
			categories = { 164, 202, 197, 755 },
		},
		{
			id = 3859,
			name = "Steel Bar",
			icon = "Interface\\Icons\\INV_Ingot_Steel",
			categories = { 164, 202 },
		},
		{
			id = 3864,
			name = "Citrine",
			icon = "Interface\\Icons\\INV_Misc_Gem_Opal_02",
			categories = { 164, 165, 197, 202, 755, 186 },
		},
		{
			id = 4234,
			name = "Heavy Leather",
			icon = "Interface\\Icons\\INV_Misc_LeatherScrap_07",
			categories = { 164, 165, 197, 202, 393 },
		},
		{
			id = 4304,
			name = "Thick Leather",
			icon = "Interface\\Icons\\INV_Misc_LeatherScrap_08",
			categories = { 197, 164, 165, 202, 393 },
		},
		{
			id = 4306,
			name = "Silk Cloth",
			icon = "Interface\\Icons\\INV_Fabric_Silk_01",
			categories = { 197, 202, 129, 164 },
		},
		{
			id = 4338,
			name = "Mageweave Cloth",
			icon = "Interface\\Icons\\INV_Fabric_Mageweave_01",
			categories = { 197, 164, 165, 129, 202 },
		},
		{
			id = 5498,
			name = "Small Lustrous Pearl",
			icon = "Interface\\Icons\\INV_Misc_Gem_Pearl_03",
			categories = { 164, 197, 165, 755 },
		},
		{
			id = 5500,
			name = "Iridescent Pearl",
			icon = "Interface\\Icons\\INV_Misc_Gem_Pearl_02",
			categories = { 164, 165, 197, 333 },
		},
		{
			id = 6037,
			name = "Truesilver Bar",
			icon = "Interface\\Icons\\INV_Ingot_08",
			categories = { 164, 197, 202, 333, 755 },
		},
		{
			id = 7075,
			name = "Core of Earth",
			icon = "Interface\\Icons\\INV_Stone_05",
			categories = { 164, 202, 165, 333, 755 },
		},
		{
			id = 7081,
			name = "Breath of Wind",
			icon = "Interface\\Icons\\Spell_Nature_Cyclone",
			categories = { 164, 333, 755, 165 },
		},
		{
			id = 7909,
			name = "Aquamarine",
			icon = "Interface\\Icons\\INV_Misc_Gem_Crystal_02",
			categories = { 164, 202, 333, 755, 186 },
		},
		{
			id = 7910,
			name = "Star Ruby",
			icon = "Interface\\Icons\\INV_Misc_Gem_Ruby_02",
			categories = { 164, 202, 197, 755, 186 },
		},
		{
			id = 7912,
			name = "Solid Stone",
			icon = "Interface\\Icons\\INV_Stone_10",
			categories = { 164, 202, 755, 186 },
		},
		{
			id = 7966,
			name = "Solid Grinding Stone",
			icon = "Interface\\Icons\\INV_Stone_GrindingStone_04",
			categories = { 164 },
		},
		{
			id = 7971,
			name = "Black Pearl",
			icon = "Interface\\Icons\\INV_Misc_Gem_Pearl_01",
			categories = { 164, 165, 333, 197, 755 },
		},
		{
			id = 8146,
			name = "Wicked Claw",
			icon = "Interface\\Icons\\INV_Misc_MonsterClaw_01",
			categories = { 164, 165 },
		},
		{
			id = 8168,
			name = "Jet Black Feather",
			icon = "Interface\\Icons\\INV_Feather_02",
			categories = { 164, 165 },
		},
		{
			id = 8170,
			name = "Rugged Leather",
			icon = "Interface\\Icons\\INV_Misc_LeatherScrap_02",
			categories = { 164, 333, 197, 165, 202, 393 },
		},
		{
			id = 11184,
			name = "Blue Power Crystal",
			icon = "Interface\\Icons\\INV_Misc_Gem_Sapphire_03",
			categories = { 164 },
		},
		{
			id = 11185,
			name = "Green Power Crystal",
			icon = "Interface\\Icons\\INV_Misc_Gem_Emerald_02",
			categories = { 164 },
		},
		{
			id = 11186,
			name = "Red Power Crystal",
			icon = "Interface\\Icons\\INV_Misc_Gem_Ruby_03",
			categories = { 164 },
		},
		{
			id = 11188,
			name = "Yellow Power Crystal",
			icon = "Interface\\Icons\\INV_Misc_Gem_Topaz_02",
			categories = { 164 },
		},
		{
			id = 11371,
			name = "Dark Iron Bar",
			icon = "Interface\\Icons\\INV_Ingot_Mithril",
			categories = { 164, 202, 755 },
		},
		{
			id = 11382,
			name = "Blood of the Mountain",
			icon = "Interface\\Icons\\INV_Misc_Gem_Bloodstone_03",
			categories = { 164, 755, 186 },
		},
		{
			id = 11754,
			name = "Black Diamond",
			icon = "Interface\\Icons\\INV_Misc_Gem_01",
			categories = { 165, 164, 755, 186 },
		},
		{
			id = 12360,
			name = "Arcanite Bar",
			icon = "Interface\\Icons\\INV_Misc_StoneTablet_05",
			categories = { 164, 202, 197, 755, 186 },
		},
		{
			id = 12361,
			name = "Blue Sapphire",
			icon = "Interface\\Icons\\INV_Misc_Gem_Sapphire_02",
			categories = { 164, 202, 755, 186 },
		},
		{
			id = 12364,
			name = "Huge Emerald",
			icon = "Interface\\Icons\\INV_Misc_Gem_Emerald_01",
			categories = { 164, 197, 202, 755, 186 },
		},
		{
			id = 12365,
			name = "Dense Stone",
			icon = "Interface\\Icons\\INV_Misc_StoneTablet_07",
			categories = { 164, 202, 755, 186 },
		},
		{
			id = 12644,
			name = "Dense Grinding Stone",
			icon = "Interface\\Icons\\INV_Stone_GrindingStone_05",
			categories = { 164 },
		},
		{
			id = 12655,
			name = "Enchanted Thorium Bar",
			icon = "Interface\\Icons\\INV_Ingot_Eternium",
			categories = { 164 },
		},
		{
			id = 12662,
			name = "Demonic Rune",
			icon = "Interface\\Icons\\INV_Misc_Rune_04",
			categories = { 164, 197, 755 },
		},
		{
			id = 12753,
			name = "Skin of Shadow",
			icon = "Interface\\Icons\\INV_Misc_ShadowEgg",
			categories = { 165, 164 },
		},
		{
			id = 12799,
			name = "Large Opal",
			icon = "Interface\\Icons\\INV_Misc_Gem_Opal_01",
			categories = { 164, 202, 755, 186 },
		},
		{
			id = 12800,
			name = "Azerothian Diamond",
			icon = "Interface\\Icons\\INV_Misc_Gem_Diamond_01",
			categories = { 164, 197, 202, 755, 186 },
		},
		{
			id = 12809,
			name = "Guardian Stone",
			icon = "Interface\\Icons\\INV_Stone_02",
			categories = { 164, 197, 165 },
		},
		{
			id = 12810,
			name = "Enchanted Leather",
			icon = "Interface\\Icons\\INV_Misc_Rune_05",
			categories = { 164, 197, 165, 202 },
		},
		{
			id = 12811,
			name = "Righteous Orb",
			icon = "Interface\\Icons\\INV_Misc_Gem_Pearl_03",
			categories = { 164, 197, 333 },
		},
		{
			id = 14047,
			name = "Runecloth",
			icon = "Interface\\Icons\\INV_Fabric_PurpleFire_01",
			categories = { 164, 197, 129, 165, 202 },
		},
		{
			id = 15417,
			name = "Devilsaur Leather",
			icon = "Interface\\Icons\\INV_Misc_Pelt_03",
			categories = { 165, 164, 393 },
		},
		{
			id = 17010,
			name = "Fiery Core",
			icon = "Interface\\Icons\\Spell_Fire_FlameBolt",
			categories = { 197, 165, 164, 202, 186 },
		},
		{
			id = 17011,
			name = "Lava Core",
			icon = "Interface\\Icons\\Spell_Nature_Earthquake",
			categories = { 197, 165, 164, 202 },
		},
		{
			id = 17012,
			name = "Core Leather",
			icon = "Interface\\Icons\\INV_Ammo_FireTar",
			categories = { 197, 165, 164, 393 },
		},
		{
			id = 17203,
			name = "Sulfuron Ingot",
			icon = "Interface\\Icons\\Spell_Fire_SealOfFire",
			categories = { 164 },
		},
		{
			id = 19726,
			name = "Bloodvine",
			icon = "Interface\\Icons\\INV_Misc_Herb_09",
			categories = { 197, 202, 164, 165, 182 },
		},
		{
			id = 19774,
			name = "Souldarite",
			icon = "Interface\\Icons\\INV_Misc_Gem_01",
			categories = { 164, 186 },
		},
		{
			id = 20520,
			name = "Dark Rune",
			icon = "Interface\\Icons\\Spell_Shadow_SealOfKings",
			categories = { 197, 164 },
		},
		{
			id = 20725,
			name = "Nexus Crystal",
			icon = "Interface\\Icons\\INV_Enchant_ShardNexusLarge",
			categories = { 164, 333 },
		},
		{
			id = 21877,
			name = "Netherweave Cloth",
			icon = "Interface\\Icons\\INV_Fabric_Netherweave",
			categories = { 197, 129, 202, 164 },
		},
		{
			id = 21887,
			name = "Knothide Leather",
			icon = "Interface\\Icons\\INV_Misc_LeatherScrap_10",
			categories = { 197, 164, 202, 165, 393 },
		},
		{
			id = 22202,
			name = "Small Obsidian Shard",
			icon = "Interface\\Icons\\INV_Misc_StoneTablet_01",
			categories = { 164, 186 },
		},
		{
			id = 22203,
			name = "Large Obsidian Shard",
			icon = "Interface\\Icons\\INV_Stone_15",
			categories = { 164, 186 },
		},
		{
			id = 22445,
			name = "Arcane Dust",
			icon = "Interface\\Icons\\INV_Enchant_DustArcane",
			categories = { 197, 333, 164, 202, 165 },
		},
		{
			id = 22449,
			name = "Large Prismatic Shard",
			icon = "Interface\\Icons\\INV_Enchant_ShardPrismaticLarge",
			categories = { 333, 164, 202 },
		},
		{
			id = 22450,
			name = "Void Crystal",
			icon = "Interface\\Icons\\INV_Enchant_VoidCrystal",
			categories = { 333, 165, 197, 164 },
		},
		{
			id = 22682,
			name = "Frozen Rune",
			icon = "Interface\\Icons\\INV_Misc_Rune_09",
			categories = { 197, 165, 164 },
		},
		{
			id = 23445,
			name = "Fel Iron Bar",
			icon = "Interface\\Icons\\INV_Ingot_FelIron",
			categories = { 186, 164, 202, 755 },
		},
		{
			id = 23446,
			name = "Adamantite Bar",
			icon = "Interface\\Icons\\INV_Ingot_10",
			categories = { 186, 164, 202, 755 },
		},
		{
			id = 23447,
			name = "Eternium Bar",
			icon = "Interface\\Icons\\INV_Ingot_11",
			categories = { 186, 164, 755 },
		},
		{
			id = 23448,
			name = "Felsteel Bar",
			icon = "Interface\\Icons\\INV_Ingot_Felsteel",
			categories = { 164, 202, 755 },
		},
		{
			id = 23449,
			name = "Khorium Bar",
			icon = "Interface\\Icons\\INV_Ingot_09",
			categories = { 164, 202, 755, 186 },
		},
		{
			id = 23572,
			name = "Primal Nether",
			icon = "Interface\\Icons\\INV_Elemental_Primal_Nether",
			categories = { 164, 197, 165, 202, 755 },
		},
		{
			id = 23573,
			name = "Hardened Adamantite Bar",
			icon = "Interface\\Icons\\INV_Ingot_Adamantite",
			categories = { 164, 202, 755, 186 },
		},
		{
			id = 23793,
			name = "Heavy Knothide Leather",
			icon = "Interface\\Icons\\INV_Misc_LeatherScrap_11",
			categories = { 202, 165, 164 },
		},
		{
			id = 32428,
			name = "Heart of Darkness",
			icon = "Interface\\Icons\\Spell_Shadow_DemonicTactics",
			categories = { 165, 197, 164 },
		},
		{
			id = 34054,
			name = "Infinite Dust",
			icon = "Interface\\Icons\\INV_Misc_Dust_Infinite",
			categories = { 333, 197, 755, 164 },
		},
		{
			id = 34664,
			name = "Sunmote",
			icon = "Interface\\Icons\\Spell_Nature_ElementalShields",
			categories = { 164, 755, 165, 197 },
		},
		{
			id = 35128,
			name = "Hardened Khorium",
			icon = "Interface\\Icons\\INV_Ingot_Thorium",
			categories = { 202, 164, 755 },
		},
		{
			id = 36916,
			name = "Cobalt Bar",
			icon = "Interface\\Icons\\INV_Ingot_Cobalt",
			categories = { 164, 202 },
		},
		{
			id = 36925,
			name = "Majestic Zircon",
			icon = "Interface\\Icons\\inv_jewelcrafting_gem_35",
			categories = { 755, 164, 197 },
		},
		{
			id = 37663,
			name = "Titansteel Bar",
			icon = "Interface\\Icons\\INV_Ingot_Titansteel_blue",
			categories = { 164, 202, 333 },
		},
		{
			id = 37700,
			name = "Crystallized Air",
			icon = "Interface\\Icons\\INV_Elemental_Crystal_Air",
			categories = { 165, 164, 202, 186 },
		},
		{
			id = 41163,
			name = "Titanium Bar",
			icon = "Interface\\Icons\\INV_Ingot_Platinum",
			categories = { 202, 333, 186, 164, 755 },
		},
		{
			id = 43102,
			name = "Frozen Orb",
			icon = "Interface\\Icons\\Spell_Frost_FrozenCore",
			categories = { 164, 197, 755, 202, 165, 773 },
		},
		{
			id = 45087,
			name = "Runed Orb",
			icon = "Interface\\Icons\\inv_misc_runedorb_01",
			categories = { 164, 165, 197 },
		},
		{
			id = 47556,
			name = "Crusader Orb",
			icon = "Interface\\Icons\\spell_holy_rune",
			categories = { 164, 165, 197 },
		},
		{
			id = 49908,
			name = "Primordial Saronite",
			icon = "Interface\\Icons\\spell_fire_felflamebreath",
			categories = { 164, 165, 197 },
		},
		{
			id = 723,
			name = "Goretusk Liver",
			icon = "Interface\\Icons\\INV_Misc_Organ_04",
			categories = { 185 },
		},
		{
			id = 729,
			name = "Stringy Vulture Meat",
			icon = "Interface\\Icons\\INV_Misc_Food_16",
			categories = { 185 },
		},
		{
			id = 730,
			name = "Murloc Eye",
			icon = "Interface\\Icons\\INV_Misc_Eye_01",
			categories = { 185 },
		},
		{
			id = 731,
			name = "Goretusk Snout",
			icon = "Interface\\Icons\\Spell_Magic_PolymorphPig",
			categories = { 185 },
		},
		{
			id = 769,
			name = "Chunk of Boar Meat",
			icon = "Interface\\Icons\\INV_Misc_Food_14",
			categories = { 185 },
		},
		{
			id = 1015,
			name = "Lean Wolf Flank",
			icon = "Interface\\Icons\\INV_Misc_Food_14",
			categories = { 185 },
		},
		{
			id = 1080,
			name = "Tough Condor Meat",
			icon = "Interface\\Icons\\INV_Misc_Food_72",
			categories = { 185 },
		},
		{
			id = 1081,
			name = "Crisp Spider Meat",
			icon = "Interface\\Icons\\INV_Misc_MonsterSpiderCarapace_01",
			categories = { 185 },
		},
		{
			id = 1468,
			name = "Murloc Fin",
			icon = "Interface\\Icons\\INV_Misc_MonsterScales_02",
			categories = { 185 },
		},
		{
			id = 2251,
			name = "Gooey Spider Leg",
			icon = "Interface\\Icons\\INV_Misc_MonsterSpiderCarapace_01",
			categories = { 185 },
		},
		{
			id = 2672,
			name = "Stringy Wolf Meat",
			icon = "Interface\\Icons\\INV_Misc_Food_14",
			categories = { 185, 186 },
		},
		{
			id = 2673,
			name = "Coyote Meat",
			icon = "Interface\\Icons\\INV_Misc_Food_69",
			categories = { 185 },
		},
		{
			id = 2674,
			name = "Crawler Meat",
			icon = "Interface\\Icons\\INV_Misc_Food_51",
			categories = { 185 },
		},
		{
			id = 2675,
			name = "Crawler Claw",
			icon = "Interface\\Icons\\INV_Misc_Birdbeck_02",
			categories = { 185 },
		},
		{
			id = 2677,
			name = "Boar Ribs",
			icon = "Interface\\Icons\\INV_Misc_Food_16",
			categories = { 185 },
		},
		{
			id = 2678,
			name = "Mild Spices",
			icon = "Interface\\Icons\\INV_Misc_Food_Wheat_02",
			categories = { 185 },
		},
		{
			id = 2886,
			name = "Crag Boar Rib",
			icon = "Interface\\Icons\\INV_Misc_Food_16",
			categories = { 185 },
		},
		{
			id = 2924,
			name = "Crocolisk Meat",
			icon = "Interface\\Icons\\INV_Misc_Food_14",
			categories = { 185 },
		},
		{
			id = 3172,
			name = "Boar Intestines",
			icon = "Interface\\Icons\\INV_Misc_Organ_05",
			categories = { 185 },
		},
		{
			id = 3173,
			name = "Bear Meat",
			icon = "Interface\\Icons\\INV_Misc_Food_71",
			categories = { 185 },
		},
		{
			id = 3174,
			name = "Spider Ichor",
			icon = "Interface\\Icons\\INV_Misc_Slime_01",
			categories = { 185 },
		},
		{
			id = 3404,
			name = "Buzzard Wing",
			icon = "Interface\\Icons\\INV_Misc_MonsterScales_02",
			categories = { 185 },
		},
		{
			id = 3667,
			name = "Tender Crocolisk Meat",
			icon = "Interface\\Icons\\INV_Misc_Food_14",
			categories = { 185 },
		},
		{
			id = 3685,
			name = "Raptor Egg",
			icon = "Interface\\Icons\\INV_Egg_03",
			categories = { 185 },
		},
		{
			id = 3712,
			name = "Turtle Meat",
			icon = "Interface\\Icons\\INV_Misc_Food_70",
			categories = { 185 },
		},
		{
			id = 3730,
			name = "Big Bear Meat",
			icon = "Interface\\Icons\\INV_Misc_Food_14",
			categories = { 185 },
		},
		{
			id = 3731,
			name = "Lion Meat",
			icon = "Interface\\Icons\\INV_Misc_Food_71",
			categories = { 185 },
		},
		{
			id = 4603,
			name = "Raw Spotted Yellowtail",
			icon = "Interface\\Icons\\INV_Misc_Fish_01",
			categories = { 185 },
		},
		{
			id = 4655,
			name = "Giant Clam Meat",
			icon = "Interface\\Icons\\INV_Misc_Food_51",
			categories = { 185 },
		},
		{
			id = 5051,
			name = "Dig Rat",
			icon = "Interface\\Icons\\INV_Misc_Pelt_Bear_Ruin_04",
			categories = { 185 },
		},
		{
			id = 5465,
			name = "Small Spider Leg",
			icon = "Interface\\Icons\\INV_Misc_MonsterSpiderCarapace_01",
			categories = { 185 },
		},
		{
			id = 5466,
			name = "Scorpid Stinger",
			icon = "Interface\\Icons\\Spell_Nature_NullifyPoison",
			categories = { 185 },
		},
		{
			id = 5467,
			name = "Kodo Meat",
			icon = "Interface\\Icons\\INV_Misc_Food_14",
			categories = { 185 },
		},
		{
			id = 5468,
			name = "Soft Frenzy Flesh",
			icon = "Interface\\Icons\\INV_Misc_Fish_04",
			categories = { 185 },
		},
		{
			id = 5469,
			name = "Strider Meat",
			icon = "Interface\\Icons\\INV_Misc_Food_16",
			categories = { 185 },
		},
		{
			id = 5470,
			name = "Thunder Lizard Tail",
			icon = "Interface\\Icons\\INV_Misc_Bone_04",
			categories = { 185 },
		},
		{
			id = 5471,
			name = "Stag Meat",
			icon = "Interface\\Icons\\INV_Misc_Pelt_Wolf_Ruin_03",
			categories = { 185 },
		},
		{
			id = 5503,
			name = "Clam Meat",
			icon = "Interface\\Icons\\INV_Misc_Food_51",
			categories = { 185 },
		},
		{
			id = 5504,
			name = "Tangy Clam Meat",
			icon = "Interface\\Icons\\INV_Misc_Food_51",
			categories = { 185 },
		},
		{
			id = 6289,
			name = "Raw Longjaw Mud Snapper",
			icon = "Interface\\Icons\\INV_Misc_Fish_32",
			categories = { 185 },
		},
		{
			id = 6291,
			name = "Raw Brilliant Smallfish",
			icon = "Interface\\Icons\\INV_Misc_Fish_08",
			categories = { 185 },
		},
		{
			id = 6303,
			name = "Raw Slitherskin Mackerel",
			icon = "Interface\\Icons\\INV_Misc_Fish_24",
			categories = { 185, 186 },
		},
		{
			id = 6308,
			name = "Raw Bristle Whisker Catfish",
			icon = "Interface\\Icons\\INV_Misc_Fish_30",
			categories = { 185 },
		},
		{
			id = 6317,
			name = "Raw Loch Frenzy",
			icon = "Interface\\Icons\\INV_Misc_Fish_03",
			categories = { 185 },
		},
		{
			id = 6361,
			name = "Raw Rainbow Fin Albacore",
			icon = "Interface\\Icons\\INV_Misc_Fish_25",
			categories = { 185 },
		},
		{
			id = 6362,
			name = "Raw Rockscale Cod",
			icon = "Interface\\Icons\\INV_Misc_Fish_04",
			categories = { 185 },
		},
		{
			id = 6889,
			name = "Small Egg",
			icon = "Interface\\Icons\\INV_Egg_01",
			categories = { 185 },
		},
		{
			id = 7974,
			name = "Zesty Clam Meat",
			icon = "Interface\\Icons\\INV_Misc_Food_51",
			categories = { 185 },
		},
		{
			id = 8150,
			name = "Deeprock Salt",
			icon = "Interface\\Icons\\INV_Misc_Dust_02",
			categories = { 165, 202, 185 },
		},
		{
			id = 8365,
			name = "Raw Mithril Head Trout",
			icon = "Interface\\Icons\\INV_Misc_Fish_02",
			categories = { 185 },
		},
		{
			id = 9061,
			name = "Goblin Rocket Fuel",
			icon = "Interface\\Icons\\INV_Cask_02",
			categories = { 202, 185 },
		},
		{
			id = 12037,
			name = "Mystery Meat",
			icon = "Interface\\Icons\\INV_Misc_Food_67",
			categories = { 185 },
		},
		{
			id = 12184,
			name = "Raptor Flesh",
			icon = "Interface\\Icons\\INV_Misc_Food_69",
			categories = { 185 },
		},
		{
			id = 12202,
			name = "Tiger Meat",
			icon = "Interface\\Icons\\INV_Misc_Food_14",
			categories = { 185 },
		},
		{
			id = 12203,
			name = "Red Wolf Meat",
			icon = "Interface\\Icons\\INV_Misc_Food_71",
			categories = { 185 },
		},
		{
			id = 12204,
			name = "Heavy Kodo Meat",
			icon = "Interface\\Icons\\INV_Misc_Food_70",
			categories = { 185 },
		},
		{
			id = 12205,
			name = "White Spider Meat",
			icon = "Interface\\Icons\\INV_Misc_Food_51",
			categories = { 185 },
		},
		{
			id = 12206,
			name = "Tender Crab Meat",
			icon = "Interface\\Icons\\INV_Misc_Food_51",
			categories = { 185 },
		},
		{
			id = 12207,
			name = "Giant Egg",
			icon = "Interface\\Icons\\INV_Egg_03",
			categories = { 185 },
		},
		{
			id = 12208,
			name = "Tender Wolf Meat",
			icon = "Interface\\Icons\\INV_Misc_Food_14",
			categories = { 185 },
		},
		{
			id = 12223,
			name = "Meaty Bat Wing",
			icon = "Interface\\Icons\\INV_Misc_Pelt_Bear_Ruin_05",
			categories = { 185, 186 },
		},
		{
			id = 13754,
			name = "Raw Glossy Mightfish",
			icon = "Interface\\Icons\\INV_Misc_MonsterHead_03",
			categories = { 185 },
		},
		{
			id = 13755,
			name = "Winter Squid",
			icon = "Interface\\Icons\\INV_Misc_Fish_13",
			categories = { 185 },
		},
		{
			id = 13756,
			name = "Raw Summer Bass",
			icon = "Interface\\Icons\\INV_Misc_Fish_03",
			categories = { 185 },
		},
		{
			id = 13757,
			name = "Lightning Eel",
			icon = "Interface\\Icons\\INV_Misc_Fish_12",
			categories = { 185 },
		},
		{
			id = 13758,
			name = "Raw Redgill",
			icon = "Interface\\Icons\\INV_Misc_Fish_06",
			categories = { 185 },
		},
		{
			id = 13759,
			name = "Raw Nightfin Snapper",
			icon = "Interface\\Icons\\INV_Misc_Fish_23",
			categories = { 185 },
		},
		{
			id = 13760,
			name = "Raw Sunscale Salmon",
			icon = "Interface\\Icons\\INV_Misc_Fish_19",
			categories = { 185 },
		},
		{
			id = 13888,
			name = "Darkclaw Lobster",
			icon = "Interface\\Icons\\INV_Misc_Fish_14",
			categories = { 185 },
		},
		{
			id = 13889,
			name = "Raw Whitescale Salmon",
			icon = "Interface\\Icons\\INV_Misc_Fish_20",
			categories = { 185 },
		},
		{
			id = 13893,
			name = "Large Raw Mightfish",
			icon = "Interface\\Icons\\INV_Misc_MonsterHead_02",
			categories = { 185 },
		},
		{
			id = 17194,
			name = "Holiday Spices",
			icon = "Interface\\Icons\\INV_Misc_Bag_11",
			categories = { 185 },
		},
		{
			id = 18255,
			name = "Runn Tum Tuber",
			icon = "Interface\\Icons\\INV_Misc_Food_55",
			categories = { 185 },
		},
		{
			id = 20424,
			name = "Sandworm Meat",
			icon = "Interface\\Icons\\INV_Misc_Food_51",
			categories = { 185 },
		},
		{
			id = 21024,
			name = "Chimaerok Tenderloin",
			icon = "Interface\\Icons\\INV_Misc_Food_70",
			categories = { 185 },
		},
		{
			id = 21071,
			name = "Raw Sagefish",
			icon = "Interface\\Icons\\INV_Misc_Fish_20",
			categories = { 185 },
		},
		{
			id = 21153,
			name = "Raw Greater Sagefish",
			icon = "Interface\\Icons\\INV_Misc_Fish_21",
			categories = { 185 },
		},
		{
			id = 22577,
			name = "Mote of Shadow",
			icon = "Interface\\Icons\\INV_Elemental_Mote_Shadow01",
			categories = { 185 },
		},
		{
			id = 22644,
			name = "Crunchy Spider Leg",
			icon = "Interface\\Icons\\INV_Misc_AhnQirajTrinket_02",
			categories = { 185 },
		},
		{
			id = 23676,
			name = "Moongraze Stag Tenderloin",
			icon = "Interface\\Icons\\INV_Misc_Food_69",
			categories = { 185 },
		},
		{
			id = 24477,
			name = "Jaggal Clam Meat",
			icon = "Interface\\Icons\\INV_Misc_Food_51",
			categories = { 185 },
		},
		{
			id = 27422,
			name = "Barbed Gill Trout",
			icon = "Interface\\Icons\\INV_Misc_Fish_37",
			categories = { 185 },
		},
		{
			id = 27425,
			name = "Spotted Feltail",
			icon = "Interface\\Icons\\INV_Misc_Fish_39",
			categories = { 185 },
		},
		{
			id = 27429,
			name = "Zangarian Sporefish",
			icon = "Interface\\Icons\\INV_Misc_Fish_34",
			categories = { 185 },
		},
		{
			id = 27435,
			name = "Figluster's Mudfish",
			icon = "Interface\\Icons\\INV_Misc_Fish_41",
			categories = { 185 },
		},
		{
			id = 27437,
			name = "Icefin Bluefish",
			icon = "Interface\\Icons\\INV_Misc_Fish_23",
			categories = { 185 },
		},
		{
			id = 27438,
			name = "Golden Darter",
			icon = "Interface\\Icons\\INV_Misc_Fish_36",
			categories = { 185 },
		},
		{
			id = 27439,
			name = "Furious Crawdad",
			icon = "Interface\\Icons\\INV_Misc_Fish_14",
			categories = { 185 },
		},
		{
			id = 27515,
			name = "Huge Spotted Feltail",
			icon = "Interface\\Icons\\INV_Misc_Fish_39",
			categories = { 185 },
		},
		{
			id = 27516,
			name = "Enormous Barbed Gill Trout",
			icon = "Interface\\Icons\\INV_Misc_Fish_37",
			categories = { 185 },
		},
		{
			id = 27668,
			name = "Lynx Meat",
			icon = "Interface\\Icons\\INV_Misc_Food_71",
			categories = { 185 },
		},
		{
			id = 27669,
			name = "Bat Flesh",
			icon = "Interface\\Icons\\INV_Misc_Food_70",
			categories = { 185 },
		},
		{
			id = 27671,
			name = "Buzzard Meat",
			icon = "Interface\\Icons\\INV_Misc_Food_82",
			categories = { 185 },
		},
		{
			id = 27674,
			name = "Ravager Flesh",
			icon = "Interface\\Icons\\INV_Misc_Food_72",
			categories = { 185 },
		},
		{
			id = 27676,
			name = "Strange Spores",
			icon = "Interface\\Icons\\INV_Misc_Dust_04",
			categories = { 185 },
		},
		{
			id = 27677,
			name = "Chunk o' Basilisk",
			icon = "Interface\\Icons\\INV_Misc_Food_81",
			categories = { 185 },
		},
		{
			id = 27678,
			name = "Clefthoof Meat",
			icon = "Interface\\Icons\\INV_Misc_Food_80",
			categories = { 185 },
		},
		{
			id = 27681,
			name = "Warped Flesh",
			icon = "Interface\\Icons\\INV_Misc_Food_83_TalbukSteak",
			categories = { 185 },
		},
		{
			id = 27682,
			name = "Talbuk Venison",
			icon = "Interface\\Icons\\INV_Misc_Food_71",
			categories = { 185 },
		},
		{
			id = 30817,
			name = "Simple Flour",
			icon = "Interface\\Icons\\INV_Misc_Food_Wheat_01",
			categories = { 185 },
		},
		{
			id = 31670,
			name = "Raptor Ribs",
			icon = "Interface\\Icons\\INV_Misc_Food_16",
			categories = { 185 },
		},
		{
			id = 31671,
			name = "Serpent Flesh",
			icon = "Interface\\Icons\\INV_Misc_Food_98_Talbuk",
			categories = { 185 },
		},
		{
			id = 33823,
			name = "Bloodfin Catfish",
			icon = "Interface\\Icons\\INV_Misc_Fish_29",
			categories = { 185 },
		},
		{
			id = 33824,
			name = "Crescent-Tail Skullfish",
			icon = "Interface\\Icons\\INV_Misc_Fish_40",
			categories = { 185 },
		},
		{
			id = 34736,
			name = "Chunk o' Mammoth",
			icon = "Interface\\Icons\\INV_Misc_Food_107_Venison",
			categories = { 185 },
		},
		{
			id = 35562,
			name = "Bear Flank",
			icon = "Interface\\Icons\\INV_Misc_Food_13",
			categories = { 185 },
		},
		{
			id = 36782,
			name = "Succulent Clam Meat",
			icon = "Interface\\Icons\\INV_Misc_Food_126_ClamMeat",
			categories = { 185 },
		},
		{
			id = 41800,
			name = "Deep Sea Monsterbelly",
			icon = "Interface\\Icons\\INV_Misc_Fish_60",
			categories = { 185 },
		},
		{
			id = 41801,
			name = "Moonglow Cuttlefish",
			icon = "Interface\\Icons\\INV_Misc_Fish_70",
			categories = { 185 },
		},
		{
			id = 41802,
			name = "Imperial Manta Ray",
			icon = "Interface\\Icons\\INV_Misc_Fish_59",
			categories = { 185 },
		},
		{
			id = 41803,
			name = "Rockfin Grouper",
			icon = "Interface\\Icons\\INV_Misc_Fish_46",
			categories = { 185 },
		},
		{
			id = 41805,
			name = "Borean Man O' War",
			icon = "Interface\\Icons\\INV_Misc_Fish_49",
			categories = { 185 },
		},
		{
			id = 41806,
			name = "Musselback Sculpin",
			icon = "Interface\\Icons\\INV_Misc_Fish_62",
			categories = { 185 },
		},
		{
			id = 41807,
			name = "Dragonfin Angelfish",
			icon = "Interface\\Icons\\INV_Misc_Fish_54",
			categories = { 185 },
		},
		{
			id = 41808,
			name = "Bonescale Snapper",
			icon = "Interface\\Icons\\INV_Misc_Fish_48",
			categories = { 185 },
		},
		{
			id = 41809,
			name = "Glacial Salmon",
			icon = "Interface\\Icons\\INV_Misc_Fish_51",
			categories = { 185 },
		},
		{
			id = 41810,
			name = "Fangtooth Herring",
			icon = "Interface\\Icons\\INV_Misc_Fish_67",
			categories = { 185 },
		},
		{
			id = 41812,
			name = "Barrelhead Goby",
			icon = "Interface\\Icons\\INV_Misc_Fish_57",
			categories = { 185 },
		},
		{
			id = 41813,
			name = "Nettlefish",
			icon = "Interface\\Icons\\INV_Misc_Fish_72",
			categories = { 185 },
		},
		{
			id = 43007,
			name = "Northern Spices",
			icon = "Interface\\Icons\\Inv_Misc_ammo_Gunpowder_05",
			categories = { 185 },
		},
		{
			id = 43009,
			name = "Shoveltusk Flank",
			icon = "Interface\\Icons\\INV_Misc_Food_135_Meat",
			categories = { 185 },
		},
		{
			id = 43010,
			name = "Worm Meat",
			icon = "Interface\\Icons\\INV_Misc_Food_137_Meat",
			categories = { 185 },
		},
		{
			id = 43011,
			name = "Worg Haunch",
			icon = "Interface\\Icons\\INV_Misc_Food_72",
			categories = { 185 },
		},
		{
			id = 43012,
			name = "Rhino Meat",
			icon = "Interface\\Icons\\INV_Misc_Food_119_RhinoMeat",
			categories = { 185 },
		},
		{
			id = 43013,
			name = "Chilled Meat",
			icon = "Interface\\Icons\\INV_Misc_Food_120_SharkMeat",
			categories = { 185 },
		},
		{
			id = 43501,
			name = "Northern Egg",
			icon = "Interface\\Icons\\INV_Egg_01",
			categories = { 185 },
		},
		{
			id = 44835,
			name = "Autumnal Herbs",
			icon = "Interface\\Icons\\INV_Misc_Herb_14",
			categories = { 185 },
		},
		{
			id = 2772,
			name = "Iron Ore",
			icon = "Interface\\Icons\\INV_Ore_Iron_01",
			categories = { 186, 333 },
		},
		{
			id = 7079,
			name = "Globe of Water",
			icon = "Interface\\Icons\\INV_Misc_Orb_01",
			categories = { 165, 197, 333, 202, 755 },
		},
		{
			id = 7392,
			name = "Green Whelp Scale",
			icon = "Interface\\Icons\\INV_Misc_MonsterScales_03",
			categories = { 165, 333, 393 },
		},
		{
			id = 10938,
			name = "Lesser Magic Essence",
			icon = "Interface\\Icons\\INV_Enchant_EssenceMagicSmall",
			categories = { 333 },
		},
		{
			id = 10939,
			name = "Greater Magic Essence",
			icon = "Interface\\Icons\\INV_Enchant_EssenceMagicLarge",
			categories = { 333 },
		},
		{
			id = 10940,
			name = "Strange Dust",
			icon = "Interface\\Icons\\INV_Enchant_DustStrange",
			categories = { 333 },
		},
		{
			id = 10978,
			name = "Small Glimmering Shard",
			icon = "Interface\\Icons\\INV_Enchant_ShardGlimmeringSmall",
			categories = { 333 },
		},
		{
			id = 10998,
			name = "Lesser Astral Essence",
			icon = "Interface\\Icons\\INV_Enchant_EssenceAstralSmall",
			categories = { 333 },
		},
		{
			id = 11082,
			name = "Greater Astral Essence",
			icon = "Interface\\Icons\\INV_Enchant_EssenceAstralLarge",
			categories = { 333 },
		},
		{
			id = 11083,
			name = "Soul Dust",
			icon = "Interface\\Icons\\INV_Enchant_DustSoul",
			categories = { 333, 755 },
		},
		{
			id = 11084,
			name = "Large Glimmering Shard",
			icon = "Interface\\Icons\\INV_Enchant_ShardGlimmeringLarge",
			categories = { 333 },
		},
		{
			id = 11134,
			name = "Lesser Mystic Essence",
			icon = "Interface\\Icons\\INV_Enchant_EssenceMysticalSmall",
			categories = { 333 },
		},
		{
			id = 11135,
			name = "Greater Mystic Essence",
			icon = "Interface\\Icons\\INV_Enchant_EssenceMysticalLarge",
			categories = { 333 },
		},
		{
			id = 11137,
			name = "Vision Dust",
			icon = "Interface\\Icons\\INV_Enchant_DustVision",
			categories = { 333, 755, 197 },
		},
		{
			id = 11138,
			name = "Small Glowing Shard",
			icon = "Interface\\Icons\\INV_Enchant_ShardGlowingSmall",
			categories = { 333 },
		},
		{
			id = 11139,
			name = "Large Glowing Shard",
			icon = "Interface\\Icons\\INV_Enchant_ShardGlowingLarge",
			categories = { 333 },
		},
		{
			id = 11174,
			name = "Lesser Nether Essence",
			icon = "Interface\\Icons\\INV_Enchant_EssenceNetherSmall",
			categories = { 333 },
		},
		{
			id = 11175,
			name = "Greater Nether Essence",
			icon = "Interface\\Icons\\INV_Enchant_EssenceNetherLarge",
			categories = { 333 },
		},
		{
			id = 11177,
			name = "Small Radiant Shard",
			icon = "Interface\\Icons\\INV_Enchant_ShardRadientSmall",
			categories = { 333 },
		},
		{
			id = 11178,
			name = "Large Radiant Shard",
			icon = "Interface\\Icons\\INV_Enchant_ShardRadientLarge",
			categories = { 333, 755 },
		},
		{
			id = 12735,
			name = "Frayed Abomination Stitching",
			icon = "Interface\\Icons\\INV_Misc_Pelt_Boar_Ruin_03",
			categories = { 0, 333 },
		},
		{
			id = 13926,
			name = "Golden Pearl",
			icon = "Interface\\Icons\\INV_Misc_Gem_Pearl_04",
			categories = { 197, 333 },
		},
		{
			id = 14343,
			name = "Small Brilliant Shard",
			icon = "Interface\\Icons\\INV_Enchant_ShardBrilliantSmall",
			categories = { 333 },
		},
		{
			id = 14344,
			name = "Large Brilliant Shard",
			icon = "Interface\\Icons\\INV_Enchant_ShardBrilliantLarge",
			categories = { 197, 333 },
		},
		{
			id = 16202,
			name = "Lesser Eternal Essence",
			icon = "Interface\\Icons\\INV_Enchant_EssenceEternalSmall",
			categories = { 333 },
		},
		{
			id = 16203,
			name = "Greater Eternal Essence",
			icon = "Interface\\Icons\\INV_Enchant_EssenceEternalLarge",
			categories = { 333, 197 },
		},
		{
			id = 16204,
			name = "Illusion Dust",
			icon = "Interface\\Icons\\INV_Enchant_DustIllusion",
			categories = { 333 },
		},
		{
			id = 17034,
			name = "Maple Seed",
			icon = "Interface\\Icons\\INV_Misc_Food_02",
			categories = { 333 },
		},
		{
			id = 17035,
			name = "Stranglethorn Seed",
			icon = "Interface\\Icons\\INV_Misc_Food_02",
			categories = { 333 },
		},
		{
			id = 22446,
			name = "Greater Planar Essence",
			icon = "Interface\\Icons\\INV_Enchant_EssenceArcaneLarge",
			categories = { 333, 197 },
		},
		{
			id = 22447,
			name = "Lesser Planar Essence",
			icon = "Interface\\Icons\\INV_Enchant_EssenceArcaneSmall",
			categories = { 333 },
		},
		{
			id = 22448,
			name = "Small Prismatic Shard",
			icon = "Interface\\Icons\\INV_Enchant_ShardPrismaticSmall",
			categories = { 333, 202, 165 },
		},
		{
			id = 22572,
			name = "Mote of Air",
			icon = "Interface\\Icons\\INV_Elemental_Mote_Air01",
			categories = { 333 },
		},
		{
			id = 23427,
			name = "Eternium Ore",
			icon = "Interface\\Icons\\INV_Ore_Eternium",
			categories = { 186, 333 },
		},
		{
			id = 34052,
			name = "Dream Shard",
			icon = "Interface\\Icons\\INV_Enchant_DreamShard_02",
			categories = { 333, 755, 202, 197 },
		},
		{
			id = 34055,
			name = "Greater Cosmic Essence",
			icon = "Interface\\Icons\\INV_Enchant_EssenceCosmicGreater",
			categories = { 333, 165 },
		},
		{
			id = 34056,
			name = "Lesser Cosmic Essence",
			icon = "Interface\\Icons\\INV_Enchant_EssenceCosmicLesser",
			categories = { 333 },
		},
		{
			id = 34057,
			name = "Abyss Crystal",
			icon = "Interface\\Icons\\INV_Enchant_AbyssCrystal",
			categories = { 333, 165 },
		},
		{
			id = 814,
			name = "Flask of Oil",
			icon = "Interface\\Icons\\INV_Drink_07",
			categories = { 202 },
		},
		{
			id = 2604,
			name = "Red Dye",
			icon = "Interface\\Icons\\INV_Potion_11",
			categories = { 197, 202, 165 },
		},
		{
			id = 4337,
			name = "Thick Spider's Silk",
			icon = "Interface\\Icons\\Spell_Nature_Web",
			categories = { 197, 165, 202 },
		},
		{
			id = 4339,
			name = "Bolt of Mageweave",
			icon = "Interface\\Icons\\INV_Fabric_Mageweave_03",
			categories = { 197, 202 },
		},
		{
			id = 4357,
			name = "Rough Blasting Powder",
			icon = "Interface\\Icons\\INV_Misc_Dust_01",
			categories = { 202 },
		},
		{
			id = 4359,
			name = "Handful of Copper Bolts",
			icon = "Interface\\Icons\\INV_Misc_Gear_06",
			categories = { 202 },
		},
		{
			id = 4361,
			name = "Copper Tube",
			icon = "Interface\\Icons\\INV_Gizmo_Pipe_02",
			categories = { 202 },
		},
		{
			id = 4363,
			name = "Copper Modulator",
			icon = "Interface\\Icons\\INV_Gizmo_03",
			categories = { 202 },
		},
		{
			id = 4364,
			name = "Coarse Blasting Powder",
			icon = "Interface\\Icons\\INV_Misc_Dust_02",
			categories = { 202 },
		},
		{
			id = 4371,
			name = "Bronze Tube",
			icon = "Interface\\Icons\\INV_Gizmo_Pipe_01",
			categories = { 202 },
		},
		{
			id = 4375,
			name = "Whirring Bronze Gizmo",
			icon = "Interface\\Icons\\INV_Gizmo_02",
			categories = { 202 },
		},
		{
			id = 4377,
			name = "Heavy Blasting Powder",
			icon = "Interface\\Icons\\INV_Misc_Dust_06",
			categories = { 202 },
		},
		{
			id = 4382,
			name = "Bronze Framework",
			icon = "Interface\\Icons\\INV_Gizmo_BronzeFramework_01",
			categories = { 202 },
		},
		{
			id = 4387,
			name = "Iron Strut",
			icon = "Interface\\Icons\\INV_Spear_05",
			categories = { 202 },
		},
		{
			id = 4389,
			name = "Gyrochronatom",
			icon = "Interface\\Icons\\INV_Misc_PocketWatch_02",
			categories = { 202 },
		},
		{
			id = 4399,
			name = "Wooden Stock",
			icon = "Interface\\Icons\\INV_Mace_11",
			categories = { 202 },
		},
		{
			id = 4400,
			name = "Heavy Stock",
			icon = "Interface\\Icons\\INV_Mace_11",
			categories = { 202 },
		},
		{
			id = 4404,
			name = "Silver Contact",
			icon = "Interface\\Icons\\INV_Ingot_04",
			categories = { 202 },
		},
		{
			id = 4407,
			name = "Accurate Scope",
			icon = "Interface\\Icons\\INV_Misc_Spyglass_02",
			categories = { 202 },
		},
		{
			id = 4611,
			name = "Blue Pearl",
			icon = "Interface\\Icons\\INV_Ore_Arcanite_02",
			categories = { 202 },
		},
		{
			id = 6260,
			name = "Blue Dye",
			icon = "Interface\\Icons\\INV_Potion_15",
			categories = { 197, 202 },
		},
		{
			id = 6530,
			name = "Nightcrawlers",
			icon = "Interface\\Icons\\INV_Misc_MonsterTail_03",
			categories = { 202 },
		},
		{
			id = 7191,
			name = "Fused Wiring",
			icon = "Interface\\Icons\\INV_Misc_Gear_03",
			categories = { 202 },
		},
		{
			id = 8151,
			name = "Flask of Mojo",
			icon = "Interface\\Icons\\INV_Potion_15",
			categories = { 165, 202, 755 },
		},
		{
			id = 9060,
			name = "Inlaid Mithril Cylinder",
			icon = "Interface\\Icons\\INV_Musket_01",
			categories = { 202 },
		},
		{
			id = 10285,
			name = "Shadow Silk",
			icon = "Interface\\Icons\\Spell_Nature_Web",
			categories = { 165, 197, 202 },
		},
		{
			id = 10505,
			name = "Solid Blasting Powder",
			icon = "Interface\\Icons\\INV_Misc_Powder_Black",
			categories = { 202 },
		},
		{
			id = 10546,
			name = "Deadly Scope",
			icon = "Interface\\Icons\\INV_Misc_Spyglass_02",
			categories = { 202 },
		},
		{
			id = 10558,
			name = "Gold Power Core",
			icon = "Interface\\Icons\\INV_Battery_02",
			categories = { 202 },
		},
		{
			id = 10559,
			name = "Mithril Tube",
			icon = "Interface\\Icons\\INV_Musket_01",
			categories = { 202 },
		},
		{
			id = 10560,
			name = "Unstable Trigger",
			icon = "Interface\\Icons\\INV_Battery_01",
			categories = { 202 },
		},
		{
			id = 10561,
			name = "Mithril Casing",
			icon = "Interface\\Icons\\INV_Gizmo_MithrilCasing_01",
			categories = { 202 },
		},
		{
			id = 10647,
			name = "Engineer's Ink",
			icon = "Interface\\Icons\\INV_Potion_65",
			categories = { 202 },
		},
		{
			id = 10648,
			name = "Common Parchment",
			icon = "Interface\\Icons\\INV_Inscription_Parchment",
			categories = { 202, 773 },
		},
		{
			id = 14227,
			name = "Ironweb Spider Silk",
			icon = "Interface\\Icons\\Spell_Nature_Web",
			categories = { 197, 165, 202 },
		},
		{
			id = 15407,
			name = "Cured Rugged Hide",
			icon = "Interface\\Icons\\INV_Misc_Pelt_Bear_03",
			categories = { 165, 202 },
		},
		{
			id = 15992,
			name = "Dense Blasting Powder",
			icon = "Interface\\Icons\\INV_Misc_Ammo_Gunpowder_01",
			categories = { 202 },
		},
		{
			id = 15994,
			name = "Thorium Widget",
			icon = "Interface\\Icons\\INV_Gizmo_04",
			categories = { 202 },
		},
		{
			id = 16000,
			name = "Thorium Tube",
			icon = "Interface\\Icons\\INV_Gizmo_Pipe_04",
			categories = { 202 },
		},
		{
			id = 16006,
			name = "Delicate Arcanite Converter",
			icon = "Interface\\Icons\\INV_Gizmo_07",
			categories = { 202 },
		},
		{
			id = 17020,
			name = "Arcane Powder",
			icon = "Interface\\Icons\\INV_Misc_Dust_01",
			categories = { 202 },
		},
		{
			id = 18631,
			name = "Truesilver Transformer",
			icon = "Interface\\Icons\\INV_Staff_18",
			categories = { 202 },
		},
		{
			id = 20816,
			name = "Delicate Copper Wire",
			icon = "Interface\\Icons\\INV_Jewelcrafting_DelicateCopperWire",
			categories = { 755, 202 },
		},
		{
			id = 21840,
			name = "Bolt of Netherweave",
			icon = "Interface\\Icons\\INV_Fabric_Netherweave_Bolt",
			categories = { 197, 202 },
		},
		{
			id = 23436,
			name = "Living Ruby",
			icon = "Interface\\Icons\\INV_Jewelcrafting_LivingRuby_02",
			categories = { 202, 755, 186 },
		},
		{
			id = 23437,
			name = "Talasite",
			icon = "Interface\\Icons\\INV_Jewelcrafting_Talasite_02",
			categories = { 202, 755, 186 },
		},
		{
			id = 23438,
			name = "Star of Elune",
			icon = "Interface\\Icons\\INV_Jewelcrafting_StarOfElune_02",
			categories = { 202, 755, 186 },
		},
		{
			id = 23439,
			name = "Noble Topaz",
			icon = "Interface\\Icons\\INV_Jewelcrafting_NobleTopaz_02",
			categories = { 202, 755, 186 },
		},
		{
			id = 23440,
			name = "Dawnstone",
			icon = "Interface\\Icons\\INV_Jewelcrafting_Dawnstone_02",
			categories = { 202, 755, 186 },
		},
		{
			id = 23441,
			name = "Nightseye",
			icon = "Interface\\Icons\\INV_Jewelcrafting_Nightseye_02",
			categories = { 202, 755, 186 },
		},
		{
			id = 23781,
			name = "Elemental Blasting Powder",
			icon = "Interface\\Icons\\Inv_Misc_ammo_Gunpowder_07",
			categories = { 202 },
		},
		{
			id = 23783,
			name = "Handful of Fel Iron Bolts",
			icon = "Interface\\Icons\\INV_Gizmo_FelIronBolts",
			categories = { 202 },
		},
		{
			id = 23784,
			name = "Adamantite Frame",
			icon = "Interface\\Icons\\INV_Gizmo_AdamantiteFrame",
			categories = { 202 },
		},
		{
			id = 23785,
			name = "Hardened Adamantite Tube",
			icon = "Interface\\Icons\\INV_Gizmo_HardenedAdamantiteTube",
			categories = { 202 },
		},
		{
			id = 23786,
			name = "Khorium Power Core",
			icon = "Interface\\Icons\\INV_Gizmo_KhoriumPowerCore",
			categories = { 202 },
		},
		{
			id = 23787,
			name = "Felsteel Stabilizer",
			icon = "Interface\\Icons\\INV_Gizmo_FelStabilizer",
			categories = { 202 },
		},
		{
			id = 24271,
			name = "Spellcloth",
			icon = "Interface\\Icons\\INV_Fabric_Spellfire",
			categories = { 197, 202 },
		},
		{
			id = 24272,
			name = "Shadowcloth",
			icon = "Interface\\Icons\\INV_Fabric_Felcloth_Ebon",
			categories = { 197, 202 },
		},
		{
			id = 32423,
			name = "Icy Blasting Primers",
			icon = "Interface\\Icons\\INV_Misc_EngGizmos_15",
			categories = { 202 },
		},
		{
			id = 33470,
			name = "Frostweave Cloth",
			icon = "Interface\\Icons\\INV_Fabric_Soulcloth",
			categories = { 129, 197, 202, 393 },
		},
		{
			id = 33568,
			name = "Borean Leather",
			icon = "Interface\\Icons\\INV_Misc_LeatherScrap_15",
			categories = { 165, 202, 393 },
		},
		{
			id = 36920,
			name = "Sun Crystal",
			icon = "Interface\\Icons\\INV_Jewelcrafting_Gem_08",
			categories = { 755, 202, 186 },
		},
		{
			id = 36922,
			name = "King's Amber",
			icon = "Interface\\Icons\\inv_jewelcrafting_gem_36",
			categories = { 755, 197, 202 },
		},
		{
			id = 38425,
			name = "Heavy Borean Leather",
			icon = "Interface\\Icons\\INV_Misc_LeatherScrap_19",
			categories = { 165, 197, 202 },
		},
		{
			id = 39681,
			name = "Handful of Cobalt Bolts",
			icon = "Interface\\Icons\\INV_Misc_EngGizmos_29",
			categories = { 202 },
		},
		{
			id = 39682,
			name = "Overcharged Capacitor",
			icon = "Interface\\Icons\\INV_Misc_EngGizmos_27",
			categories = { 202 },
		},
		{
			id = 39683,
			name = "Froststeel Tube",
			icon = "Interface\\Icons\\INV_Misc_EngGizmos_28",
			categories = { 202 },
		},
		{
			id = 39684,
			name = "Hair Trigger",
			icon = "Interface\\Icons\\INV_Misc_EngGizmos_25",
			categories = { 202 },
		},
		{
			id = 39690,
			name = "Volatile Blasting Trigger",
			icon = "Interface\\Icons\\INV_Misc_EngGizmos_04",
			categories = { 202 },
		},
		{
			id = 40533,
			name = "Walnut Stock",
			icon = "Interface\\Icons\\INV_Mace_11",
			categories = { 202 },
		},
		{
			id = 41146,
			name = "Sun Scope",
			icon = "Interface\\Icons\\INV_Misc_Spyglass_03",
			categories = { 202 },
		},
		{
			id = 42546,
			name = "Mana Injector Kit",
			icon = "Interface\\Icons\\INV_Gizmo_04",
			categories = { 202 },
		},
		{
			id = 44128,
			name = "Arctic Fur",
			icon = "Interface\\Icons\\INV_Misc_Pelt_14",
			categories = { 165, 202, 393 },
		},
		{
			id = 44499,
			name = "Salvaged Iron Golem Parts",
			icon = "Interface\\Icons\\INV_Misc_EngGizmos_19",
			categories = { 202 },
		},
		{
			id = 44500,
			name = "Elementium-plated Exhaust Pipe",
			icon = "Interface\\Icons\\INV_Gizmo_Pipe_02",
			categories = { 202 },
		},
		{
			id = 44501,
			name = "Goblin-machined Piston",
			icon = "Interface\\Icons\\INV_Rod_Platinum",
			categories = { 202 },
		},
		{
			id = 1475,
			name = "Small Venom Sac",
			icon = "Interface\\Icons\\INV_Misc_Organ_02",
			categories = { 129 },
		},
		{
			id = 19441,
			name = "Huge Venom Sac",
			icon = "Interface\\Icons\\INV_Misc_Organ_04",
			categories = { 129 },
		},
		{
			id = 5056,
			name = "Root Sample",
			icon = "Interface\\Icons\\INV_Misc_Herb_07",
			categories = { 182 },
		},
		{
			id = 11514,
			name = "Fel Creep",
			icon = "Interface\\Icons\\Spell_Nature_Acid_01",
			categories = { 0, 182 },
		},
		{
			id = 22575,
			name = "Mote of Life",
			icon = "Interface\\Icons\\INV_Elemental_Mote_Life01",
			categories = { 182 },
		},
		{
			id = 22576,
			name = "Mote of Mana",
			icon = "Interface\\Icons\\INV_Elemental_Mote_Mana",
			categories = { 182 },
		},
		{
			id = 22710,
			name = "Bloodthistle",
			icon = "Interface\\Icons\\INV_Misc_Herb_11",
			categories = { 182 },
		},
		{
			id = 24401,
			name = "Unidentified Plant Parts",
			icon = "Interface\\Icons\\INV_Misc_Flower_03",
			categories = { 182 },
		},
		{
			id = 32468,
			name = "Netherdust Pollen",
			icon = "Interface\\Icons\\INV_Enchant_DustSoul",
			categories = { 182 },
		},
		{
			id = 32506,
			name = "Netherwing Egg",
			icon = "Interface\\Icons\\INV_Misc_ShadowEgg",
			categories = { 186, 182 },
		},
		{
			id = 35229,
			name = "Nether Residue",
			icon = "Interface\\Icons\\INV_Misc_Dust_03",
			categories = { 393, 186, 182 },
		},
		{
			id = 37101,
			name = "Ivory Ink",
			icon = "Interface\\Icons\\INV_Inscription_InkWhite03",
			categories = { 773 },
		},
		{
			id = 39151,
			name = "Alabaster Pigment",
			icon = "Interface\\Icons\\INV_Inscription_Pigment_White",
			categories = { 773 },
		},
		{
			id = 39334,
			name = "Dusky Pigment",
			icon = "Interface\\Icons\\INV_Inscription_Pigment_Grey",
			categories = { 773 },
		},
		{
			id = 39338,
			name = "Golden Pigment",
			icon = "Interface\\Icons\\INV_Inscription_Pigment_Golden",
			categories = { 773 },
		},
		{
			id = 39339,
			name = "Emerald Pigment",
			icon = "Interface\\Icons\\INV_Inscription_Pigment_Emerald",
			categories = { 773 },
		},
		{
			id = 39340,
			name = "Violet Pigment",
			icon = "Interface\\Icons\\INV_Inscription_Pigment_Violet",
			categories = { 773 },
		},
		{
			id = 39341,
			name = "Silvery Pigment",
			icon = "Interface\\Icons\\INV_Inscription_Pigment_Silvery",
			categories = { 773 },
		},
		{
			id = 39342,
			name = "Nether Pigment",
			icon = "Interface\\Icons\\INV_Inscription_Pigment_Nether",
			categories = { 773 },
		},
		{
			id = 39343,
			name = "Azure Pigment",
			icon = "Interface\\Icons\\INV_Inscription_Pigment_Azure",
			categories = { 773 },
		},
		{
			id = 39354,
			name = "Light Parchment",
			icon = "Interface\\Icons\\INV_Inscription_Papyrus",
			categories = { 773 },
		},
		{
			id = 39469,
			name = "Moonglow Ink",
			icon = "Interface\\Icons\\INV_Inscription_InkWhite02",
			categories = { 773 },
		},
		{
			id = 39501,
			name = "Heavy Parchment",
			icon = "Interface\\Icons\\INV_Inscription_Scroll",
			categories = { 773 },
		},
		{
			id = 39502,
			name = "Resilient Parchment",
			icon = "Interface\\Icons\\INV_Inscription_Certificate",
			categories = { 773 },
		},
		{
			id = 39774,
			name = "Midnight Ink",
			icon = "Interface\\Icons\\INV_Inscription_InkBlack01",
			categories = { 773 },
		},
		{
			id = 43103,
			name = "Verdant Pigment",
			icon = "Interface\\Icons\\INV_Inscription_Pigment_Verdant",
			categories = { 773 },
		},
		{
			id = 43104,
			name = "Burnt Pigment",
			icon = "Interface\\Icons\\INV_Inscription_Pigment_Burnt",
			categories = { 773 },
		},
		{
			id = 43105,
			name = "Indigo Pigment",
			icon = "Interface\\Icons\\INV_Inscription_Pigment_Indigo",
			categories = { 773 },
		},
		{
			id = 43106,
			name = "Ruby Pigment",
			icon = "Interface\\Icons\\INV_Inscription_Pigment_Ruby",
			categories = { 773 },
		},
		{
			id = 43107,
			name = "Sapphire Pigment",
			icon = "Interface\\Icons\\INV_Inscription_Pigment_Sapphire",
			categories = { 773 },
		},
		{
			id = 43108,
			name = "Ebon Pigment",
			icon = "Interface\\Icons\\INV_Inscription_Pigment_Ebon",
			categories = { 773 },
		},
		{
			id = 43109,
			name = "Icy Pigment",
			icon = "Interface\\Icons\\INV_Inscription_Pigment_Icy",
			categories = { 773 },
		},
		{
			id = 43115,
			name = "Hunter's Ink",
			icon = "Interface\\Icons\\INV_Inscription_InkGreen02",
			categories = { 773 },
		},
		{
			id = 43116,
			name = "Lion's Ink",
			icon = "Interface\\Icons\\INV_Inscription_InkYellow02",
			categories = { 773 },
		},
		{
			id = 43117,
			name = "Dawnstar Ink",
			icon = "Interface\\Icons\\INV_Inscription_InkYellow04",
			categories = { 773 },
		},
		{
			id = 43118,
			name = "Jadefire Ink",
			icon = "Interface\\Icons\\INV_Inscription_InkGreen03",
			categories = { 773 },
		},
		{
			id = 43119,
			name = "Royal Ink",
			icon = "Interface\\Icons\\INV_Inscription_InkPurple04",
			categories = { 773 },
		},
		{
			id = 43120,
			name = "Celestial Ink",
			icon = "Interface\\Icons\\INV_Inscription_InkPurple03",
			categories = { 773 },
		},
		{
			id = 43121,
			name = "Fiery Ink",
			icon = "Interface\\Icons\\INV_Inscription_InkRed01",
			categories = { 773 },
		},
		{
			id = 43122,
			name = "Shimmering Ink",
			icon = "Interface\\Icons\\INV_Inscription_InkSilver01",
			categories = { 773 },
		},
		{
			id = 43123,
			name = "Ink of the Sky",
			icon = "Interface\\Icons\\INV_Inscription_InkBlueWhite03",
			categories = { 773 },
		},
		{
			id = 43124,
			name = "Ethereal Ink",
			icon = "Interface\\Icons\\INV_Inscription_InkBlack02",
			categories = { 773 },
		},
		{
			id = 43125,
			name = "Darkflame Ink",
			icon = "Interface\\Icons\\INV_Inscription_InkBlack04",
			categories = { 773 },
		},
		{
			id = 43126,
			name = "Ink of the Sea",
			icon = "Interface\\Icons\\INV_Inscription_InkPurple01",
			categories = { 773 },
		},
		{
			id = 43127,
			name = "Snowfall Ink",
			icon = "Interface\\Icons\\INV_Inscription_InkBlueWhite01",
			categories = { 773 },
		},
		{
			id = 8152,
			name = "Flask of Big Mojo",
			icon = "Interface\\Icons\\INV_Potion_12",
			categories = { 165, 755 },
		},
		{
			id = 18335,
			name = "Pristine Black Diamond",
			icon = "Interface\\Icons\\INV_Misc_Gem_02",
			categories = { 755 },
		},
		{
			id = 20817,
			name = "Bronze Setting",
			icon = "Interface\\Icons\\INV_Jewelcrafting_BronzeSetting",
			categories = { 755 },
		},
		{
			id = 20963,
			name = "Mithril Filigree",
			icon = "Interface\\Icons\\INV_Jewelcrafting_MithrilFiligree",
			categories = { 755 },
		},
		{
			id = 21752,
			name = "Thorium Setting",
			icon = "Interface\\Icons\\INV_Jewelcrafting_ThoriumSetting",
			categories = { 755 },
		},
		{
			id = 24243,
			name = "Adamantite Powder",
			icon = "Interface\\Icons\\INV_Misc_Powder_Adamantite",
			categories = { 755 },
		},
		{
			id = 24478,
			name = "Jaggal Pearl",
			icon = "Interface\\Icons\\INV_Misc_Gem_Pearl_02",
			categories = { 755 },
		},
		{
			id = 24479,
			name = "Shadow Pearl",
			icon = "Interface\\Icons\\INV_Misc_Gem_Pearl_01",
			categories = { 755 },
		},
		{
			id = 31079,
			name = "Mercurial Adamantite",
			icon = "Interface\\Icons\\Spell_Arcane_ArcanePotency",
			categories = { 755 },
		},
		{
			id = 32227,
			name = "Crimson Spinel",
			icon = "Interface\\Icons\\INV_Jewelcrafting_CrimsonSpinel_01",
			categories = { 755, 186 },
		},
		{
			id = 32228,
			name = "Empyrean Sapphire",
			icon = "Interface\\Icons\\INV_Jewelcrafting_EmpyreanSapphire_01",
			categories = { 755, 186 },
		},
		{
			id = 32229,
			name = "Lionseye",
			icon = "Interface\\Icons\\INV_Jewelcrafting_Lionseye_01",
			categories = { 755, 186 },
		},
		{
			id = 32230,
			name = "Shadowsong Amethyst",
			icon = "Interface\\Icons\\INV_Jewelcrafting_ShadowsongAmethyst_01",
			categories = { 755, 186 },
		},
		{
			id = 32231,
			name = "Pyrestone",
			icon = "Interface\\Icons\\INV_Jewelcrafting_Pyrestone_01",
			categories = { 755, 186 },
		},
		{
			id = 32249,
			name = "Seaspray Emerald",
			icon = "Interface\\Icons\\INV_Jewelcrafting_SeasprayEmerald_01",
			categories = { 755, 186 },
		},
		{
			id = 36783,
			name = "Northsea Pearl",
			icon = "Interface\\Icons\\INV_Misc_Gem_Pearl_09",
			categories = { 197, 755 },
		},
		{
			id = 36784,
			name = "Siren's Tear",
			icon = "Interface\\Icons\\INV_Misc_Gem_Pearl_11",
			categories = { 197, 755 },
		},
		{
			id = 36919,
			name = "Cardinal Ruby",
			icon = "Interface\\Icons\\inv_jewelcrafting_gem_32",
			categories = { 755, 197 },
		},
		{
			id = 36926,
			name = "Shadow Crystal",
			icon = "Interface\\Icons\\INV_Jewelcrafting_Gem_11",
			categories = { 755, 186 },
		},
		{
			id = 36928,
			name = "Dreadstone",
			icon = "Interface\\Icons\\inv_jewelcrafting_gem_31",
			categories = { 755 },
		},
		{
			id = 36931,
			name = "Ametrine",
			icon = "Interface\\Icons\\inv_jewelcrafting_gem_33",
			categories = { 755 },
		},
		{
			id = 36934,
			name = "Eye of Zul",
			icon = "Interface\\Icons\\inv_jewelcrafting_gem_34",
			categories = { 755, 197 },
		},
		{
			id = 41266,
			name = "Skyflare Diamond",
			icon = "Interface\\Icons\\INV_Jewelcrafting_IceDiamond_01",
			categories = { 755 },
		},
		{
			id = 41334,
			name = "Earthsiege Diamond",
			icon = "Interface\\Icons\\INV_Jewelcrafting_ShadowSpirit_01",
			categories = { 755 },
		},
		{
			id = 42225,
			name = "Dragon's Eye",
			icon = "Interface\\Icons\\INV_Jewelcrafting_DragonsEye01",
			categories = { 755 },
		},
		{
			id = 783,
			name = "Light Hide",
			icon = "Interface\\Icons\\INV_Misc_Pelt_Wolf_Ruin_02",
			categories = { 165, 393 },
		},
		{
			id = 2320,
			name = "Coarse Thread",
			icon = "Interface\\Icons\\INV_Fabric_Linen_03",
			categories = { 165, 197 },
		},
		{
			id = 2324,
			name = "Bleach",
			icon = "Interface\\Icons\\INV_Drink_12",
			categories = { 165, 197 },
		},
		{
			id = 2325,
			name = "Black Dye",
			icon = "Interface\\Icons\\INV_Potion_63",
			categories = { 197, 165 },
		},
		{
			id = 2934,
			name = "Ruined Leather Scraps",
			icon = "Interface\\Icons\\INV_Misc_Pelt_Bear_Ruin_05",
			categories = { 165, 393 },
		},
		{
			id = 2997,
			name = "Bolt of Woolen Cloth",
			icon = "Interface\\Icons\\INV_Fabric_Wool_03",
			categories = { 197, 165 },
		},
		{
			id = 3182,
			name = "Spider's Silk",
			icon = "Interface\\Icons\\Spell_Nature_Web",
			categories = { 165, 197 },
		},
		{
			id = 4096,
			name = "Coarse Gorilla Hair",
			icon = "Interface\\Icons\\INV_Misc_MonsterTail_03",
			categories = { 165 },
		},
		{
			id = 4231,
			name = "Cured Light Hide",
			icon = "Interface\\Icons\\INV_Misc_Pelt_Wolf_01",
			categories = { 165 },
		},
		{
			id = 4232,
			name = "Medium Hide",
			icon = "Interface\\Icons\\INV_Misc_Pelt_Boar_Ruin_02",
			categories = { 165, 393 },
		},
		{
			id = 4233,
			name = "Cured Medium Hide",
			icon = "Interface\\Icons\\INV_Misc_Pelt_Bear_02",
			categories = { 165 },
		},
		{
			id = 4235,
			name = "Heavy Hide",
			icon = "Interface\\Icons\\INV_Misc_Pelt_Wolf_Ruin_03",
			categories = { 165, 393 },
		},
		{
			id = 4236,
			name = "Cured Heavy Hide",
			icon = "Interface\\Icons\\INV_Misc_Pelt_Wolf_02",
			categories = { 165 },
		},
		{
			id = 4289,
			name = "Salt",
			icon = "Interface\\Icons\\INV_Misc_Dust_02",
			categories = { 165 },
		},
		{
			id = 4291,
			name = "Silken Thread",
			icon = "Interface\\Icons\\INV_Fabric_Silk_02",
			categories = { 165, 197 },
		},
		{
			id = 4305,
			name = "Bolt of Silk Cloth",
			icon = "Interface\\Icons\\INV_Fabric_Silk_03",
			categories = { 197, 165 },
		},
		{
			id = 4340,
			name = "Gray Dye",
			icon = "Interface\\Icons\\INV_Drink_10",
			categories = { 165, 197 },
		},
		{
			id = 4461,
			name = "Raptor Hide",
			icon = "Interface\\Icons\\INV_Misc_MonsterScales_01",
			categories = { 165 },
		},
		{
			id = 5082,
			name = "Thin Kodo Leather",
			icon = "Interface\\Icons\\INV_Misc_LeatherScrap_06",
			categories = { 165 },
		},
		{
			id = 5116,
			name = "Long Tail Feather",
			icon = "Interface\\Icons\\INV_Feather_03",
			categories = { 165 },
		},
		{
			id = 5373,
			name = "Lucky Charm",
			icon = "Interface\\Icons\\INV_Misc_ArmorKit_06",
			categories = { 165 },
		},
		{
			id = 5784,
			name = "Slimy Murloc Scale",
			icon = "Interface\\Icons\\INV_Misc_MonsterScales_02",
			categories = { 165 },
		},
		{
			id = 5785,
			name = "Thick Murloc Scale",
			icon = "Interface\\Icons\\INV_Misc_MonsterScales_03",
			categories = { 165 },
		},
		{
			id = 6470,
			name = "Deviate Scale",
			icon = "Interface\\Icons\\INV_Misc_MonsterScales_02",
			categories = { 165, 393 },
		},
		{
			id = 6471,
			name = "Perfect Deviate Scale",
			icon = "Interface\\Icons\\INV_Misc_MonsterScales_01",
			categories = { 165, 393 },
		},
		{
			id = 7071,
			name = "Iron Buckle",
			icon = "Interface\\Icons\\INV_Misc_ArmorKit_12",
			categories = { 165, 197 },
		},
		{
			id = 7286,
			name = "Black Whelp Scale",
			icon = "Interface\\Icons\\INV_Misc_MonsterScales_03",
			categories = { 165, 393 },
		},
		{
			id = 7287,
			name = "Red Whelp Scale",
			icon = "Interface\\Icons\\INV_Misc_MonsterScales_02",
			categories = { 165, 393 },
		},
		{
			id = 8154,
			name = "Scorpid Scale",
			icon = "Interface\\Icons\\INV_Misc_MonsterScales_02",
			categories = { 165, 393 },
		},
		{
			id = 8165,
			name = "Worn Dragonscale",
			icon = "Interface\\Icons\\INV_Misc_MonsterScales_17",
			categories = { 165, 393 },
		},
		{
			id = 8167,
			name = "Turtle Scale",
			icon = "Interface\\Icons\\INV_Misc_MonsterScales_11",
			categories = { 165, 393 },
		},
		{
			id = 8169,
			name = "Thick Hide",
			icon = "Interface\\Icons\\INV_Misc_Pelt_Bear_Ruin_01",
			categories = { 165, 393 },
		},
		{
			id = 8171,
			name = "Rugged Hide",
			icon = "Interface\\Icons\\INV_Misc_Pelt_Bear_Ruin_02",
			categories = { 165, 393 },
		},
		{
			id = 8172,
			name = "Cured Thick Hide",
			icon = "Interface\\Icons\\INV_Misc_Pelt_Bear_01",
			categories = { 165 },
		},
		{
			id = 8343,
			name = "Heavy Silken Thread",
			icon = "Interface\\Icons\\INV_Fabric_Silk_02",
			categories = { 165, 197 },
		},
		{
			id = 12607,
			name = "Brilliant Chromatic Scale",
			icon = "Interface\\Icons\\INV_Misc_MonsterScales_17",
			categories = { 165, 393 },
		},
		{
			id = 14048,
			name = "Bolt of Runecloth",
			icon = "Interface\\Icons\\INV_Fabric_PurpleFire_02",
			categories = { 197, 165 },
		},
		{
			id = 14256,
			name = "Felcloth",
			icon = "Interface\\Icons\\INV_Fabric_FelRag",
			categories = { 197, 165 },
		},
		{
			id = 14341,
			name = "Rune Thread",
			icon = "Interface\\Icons\\Spell_Shadow_AntiMagicShell",
			categories = { 197, 165 },
		},
		{
			id = 14342,
			name = "Mooncloth",
			icon = "Interface\\Icons\\INV_Fabric_MoonRag_01",
			categories = { 197, 165 },
		},
		{
			id = 15408,
			name = "Heavy Scorpid Scale",
			icon = "Interface\\Icons\\INV_Misc_MonsterScales_03",
			categories = { 165, 393 },
		},
		{
			id = 15409,
			name = "Refined Deeprock Salt",
			icon = "Interface\\Icons\\INV_Misc_Dust_01",
			categories = { 165 },
		},
		{
			id = 15410,
			name = "Scale of Onyxia",
			icon = "Interface\\Icons\\INV_Misc_MonsterScales_07",
			categories = { 165, 393 },
		},
		{
			id = 15412,
			name = "Green Dragonscale",
			icon = "Interface\\Icons\\INV_Misc_MonsterScales_11",
			categories = { 165, 393 },
		},
		{
			id = 15414,
			name = "Red Dragonscale",
			icon = "Interface\\Icons\\INV_Misc_MonsterScales_15",
			categories = { 165, 393 },
		},
		{
			id = 15415,
			name = "Blue Dragonscale",
			icon = "Interface\\Icons\\INV_Misc_MonsterScales_09",
			categories = { 165, 393 },
		},
		{
			id = 15416,
			name = "Black Dragonscale",
			icon = "Interface\\Icons\\INV_Misc_MonsterScales_07",
			categories = { 165, 393 },
		},
		{
			id = 15419,
			name = "Warbear Leather",
			icon = "Interface\\Icons\\INV_Misc_Pelt_Bear_Ruin_05",
			categories = { 165, 393 },
		},
		{
			id = 15420,
			name = "Ironfeather",
			icon = "Interface\\Icons\\INV_Feather_05",
			categories = { 165 },
		},
		{
			id = 17056,
			name = "Light Feather",
			icon = "Interface\\Icons\\INV_Feather_04",
			categories = { 165, 186 },
		},
		{
			id = 18240,
			name = "Ogre Tannin",
			icon = "Interface\\Icons\\INV_Potion_08",
			categories = { 197, 165 },
		},
		{
			id = 18512,
			name = "Larval Acid",
			icon = "Interface\\Icons\\INV_Potion_22",
			categories = { 165 },
		},
		{
			id = 19767,
			name = "Primal Bat Leather",
			icon = "Interface\\Icons\\INV_Misc_Pelt_01",
			categories = { 165, 393 },
		},
		{
			id = 19768,
			name = "Primal Tiger Leather",
			icon = "Interface\\Icons\\INV_Misc_Pelt_04",
			categories = { 165, 393 },
		},
		{
			id = 20381,
			name = "Dreamscale",
			icon = "Interface\\Icons\\INV_Misc_MonsterScales_11",
			categories = { 165, 393 },
		},
		{
			id = 20498,
			name = "Silithid Chitin",
			icon = "Interface\\Icons\\INV_Misc_MonsterScales_13",
			categories = { 165, 393 },
		},
		{
			id = 20500,
			name = "Light Silithid Carapace",
			icon = "Interface\\Icons\\INV_Misc_MonsterScales_14",
			categories = { 165, 393 },
		},
		{
			id = 20501,
			name = "Heavy Silithid Carapace",
			icon = "Interface\\Icons\\INV_Misc_MonsterScales_05",
			categories = { 165, 393 },
		},
		{
			id = 21844,
			name = "Bolt of Soulcloth",
			icon = "Interface\\Icons\\INV_Fabric_Soulcloth_Bolt",
			categories = { 197, 165 },
		},
		{
			id = 25649,
			name = "Knothide Leather Scraps",
			icon = "Interface\\Icons\\INV_Misc_LeatherScrap_09",
			categories = { 165, 393 },
		},
		{
			id = 25699,
			name = "Crystal Infused Leather",
			icon = "Interface\\Icons\\INV_Misc_LeatherScrap_12",
			categories = { 165, 393 },
		},
		{
			id = 25700,
			name = "Fel Scales",
			icon = "Interface\\Icons\\INV_Misc_MonsterScales_04",
			categories = { 165, 393 },
		},
		{
			id = 25707,
			name = "Fel Hide",
			icon = "Interface\\Icons\\INV_Misc_LeatherScrap_13",
			categories = { 165, 393 },
		},
		{
			id = 25708,
			name = "Thick Clefthoof Leather",
			icon = "Interface\\Icons\\INV_Misc_LeatherScrap_14",
			categories = { 165, 393 },
		},
		{
			id = 25719,
			name = "Arakkoa Feather",
			icon = "Interface\\Icons\\INV_Feather_06",
			categories = { 165 },
		},
		{
			id = 29539,
			name = "Cobra Scales",
			icon = "Interface\\Icons\\INV_Misc_MonsterScales_18",
			categories = { 165, 393 },
		},
		{
			id = 29547,
			name = "Wind Scales",
			icon = "Interface\\Icons\\INV_Misc_MonsterScales_06",
			categories = { 165, 393 },
		},
		{
			id = 29548,
			name = "Nether Dragonscales",
			icon = "Interface\\Icons\\INV_Misc_MonsterScales_10",
			categories = { 165, 393 },
		},
		{
			id = 33567,
			name = "Borean Leather Scraps",
			icon = "Interface\\Icons\\INV_Misc_LeatherScrap_16",
			categories = { 165, 393 },
		},
		{
			id = 38557,
			name = "Icy Dragonscale",
			icon = "Interface\\Icons\\INV_Misc_MonsterScales_19",
			categories = { 165, 393 },
		},
		{
			id = 38558,
			name = "Nerubian Chitin",
			icon = "Interface\\Icons\\INV_Misc_NerubianChitin_01",
			categories = { 165, 393 },
		},
		{
			id = 38561,
			name = "Jormungar Scale",
			icon = "Interface\\Icons\\INV_Misc_MonsterScales_18",
			categories = { 165, 393 },
		},
		{
			id = 2770,
			name = "Copper Ore",
			icon = "Interface\\Icons\\INV_Ore_Copper_01",
			categories = { 186 },
		},
		{
			id = 2771,
			name = "Tin Ore",
			icon = "Interface\\Icons\\INV_Ore_Tin_01",
			categories = { 186 },
		},
		{
			id = 2775,
			name = "Silver Ore",
			icon = "Interface\\Icons\\INV_Stone_16",
			categories = { 186 },
		},
		{
			id = 2776,
			name = "Gold Ore",
			icon = "Interface\\Icons\\INV_Ore_Gold_01",
			categories = { 186 },
		},
		{
			id = 2798,
			name = "Rethban Ore",
			icon = "Interface\\Icons\\INV_Ore_Iron_01",
			categories = { 186 },
		},
		{
			id = 3340,
			name = "Incendicite Ore",
			icon = "Interface\\Icons\\INV_Ore_Thorium_01",
			categories = { 186 },
		},
		{
			id = 3576,
			name = "Tin Bar",
			icon = "Interface\\Icons\\INV_Ingot_05",
			categories = { 186 },
		},
		{
			id = 3857,
			name = "Coal",
			icon = "Interface\\Icons\\INV_Ore_Tin_01",
			categories = { 186 },
		},
		{
			id = 4278,
			name = "Lesser Bloodstone Ore",
			icon = "Interface\\Icons\\INV_Ore_Thorium_01",
			categories = { 186 },
		},
		{
			id = 5075,
			name = "Blood Shard",
			icon = "Interface\\Icons\\INV_Misc_Gem_Ruby_01",
			categories = { 186 },
		},
		{
			id = 5833,
			name = "Indurium Ore",
			icon = "Interface\\Icons\\INV_Ore_Mithril_01",
			categories = { 186 },
		},
		{
			id = 7911,
			name = "Truesilver Ore",
			icon = "Interface\\Icons\\INV_Ore_TrueSilver_01",
			categories = { 186 },
		},
		{
			id = 11370,
			name = "Dark Iron Ore",
			icon = "Interface\\Icons\\INV_Ore_Mithril_01",
			categories = { 186 },
		},
		{
			id = 11513,
			name = "Tainted Vitriol",
			icon = "Interface\\Icons\\INV_Misc_Gem_Pearl_01",
			categories = { 0, 186 },
		},
		{
			id = 18562,
			name = "Elementium Ore",
			icon = "Interface\\Icons\\INV_Stone_SharpeningStone_01",
			categories = { 186 },
		},
		{
			id = 18567,
			name = "Elemental Flux",
			icon = "Interface\\Icons\\Spell_Frost_FireResistanceTotem",
			categories = { 186 },
		},
		{
			id = 22634,
			name = "Underlight Ore",
			icon = "Interface\\Icons\\INV_Ore_Mithril_01",
			categories = { 186 },
		},
		{
			id = 23424,
			name = "Fel Iron Ore",
			icon = "Interface\\Icons\\INV_Ore_FelIron",
			categories = { 186 },
		},
		{
			id = 23425,
			name = "Adamantite Ore",
			icon = "Interface\\Icons\\INV_Ore_Adamantium",
			categories = { 186 },
		},
		{
			id = 23426,
			name = "Khorium Ore",
			icon = "Interface\\Icons\\INV_Ore_Khorium",
			categories = { 186 },
		},
		{
			id = 32464,
			name = "Nethercite Ore",
			icon = "Interface\\Icons\\INV_Ore_Ethernium_01",
			categories = { 186 },
		},
		{
			id = 36728,
			name = "Ice Shard Cluster",
			icon = "Interface\\Icons\\INV_Jewelry_Talisman_17",
			categories = { 186 },
		},
		{
			id = 36909,
			name = "Cobalt Ore",
			icon = "Interface\\Icons\\INV_Ore_Cobalt",
			categories = { 186 },
		},
		{
			id = 36910,
			name = "Titanium Ore",
			icon = "Interface\\Icons\\INV_Ore_Platinum_01",
			categories = { 186 },
		},
		{
			id = 36912,
			name = "Saronite Ore",
			icon = "Interface\\Icons\\INV_Ore_Saronite_01",
			categories = { 186 },
		},
		{
			id = 7428,
			name = "Shadowcat Hide",
			icon = "Interface\\Icons\\INV_Misc_Pelt_01",
			categories = { 393 },
		},
		{
			id = 8368,
			name = "Thick Wolfhide",
			icon = "Interface\\Icons\\INV_Misc_Pelt_02",
			categories = { 393 },
		},
		{
			id = 8973,
			name = "Thick Yeti Hide",
			icon = "Interface\\Icons\\INV_Misc_Pelt_Boar_01",
			categories = { 393 },
		},
		{
			id = 11512,
			name = "Patch of Tainted Skin",
			icon = "Interface\\Icons\\INV_Misc_Pelt_02",
			categories = { 0, 393 },
		},
		{
			id = 12366,
			name = "Thick Yeti Fur",
			icon = "Interface\\Icons\\INV_Misc_Pelt_03",
			categories = { 393 },
		},
		{
			id = 12731,
			name = "Pristine Hide of the Beast",
			icon = "Interface\\Icons\\INV_Misc_MonsterScales_15",
			categories = { 393 },
		},
		{
			id = 15422,
			name = "Frostsaber Leather",
			icon = "Interface\\Icons\\INV_Misc_Pelt_06",
			categories = { 393 },
		},
		{
			id = 15423,
			name = "Chimera Leather",
			icon = "Interface\\Icons\\INV_Misc_LeatherScrap_01",
			categories = { 393 },
		},
		{
			id = 17057,
			name = "Shiny Fish Scales",
			icon = "Interface\\Icons\\INV_Misc_MonsterScales_08",
			categories = { 393 },
		},
		{
			id = 18947,
			name = "Rage Scar Yeti Hide",
			icon = "Interface\\Icons\\INV_Misc_Pelt_Bear_Ruin_04",
			categories = { 393 },
		},
		{
			id = 23677,
			name = "Moongraze Buck Hide",
			icon = "Interface\\Icons\\INV_Misc_Pelt_02",
			categories = { 393 },
		},
		{
			id = 32470,
			name = "Nethermine Flayer Hide",
			icon = "Interface\\Icons\\INV_Misc_Rune_12",
			categories = { 393 },
		},
		{
			id = 36729,
			name = "Thin Animal Hide",
			icon = "Interface\\Icons\\INV_Misc_LeatherScrap_13",
			categories = { 393 },
		},
		{
			id = 42510,
			name = "Worg Fur",
			icon = "Interface\\Icons\\INV_Misc_Pelt_Wolf_01",
			categories = { 393 },
		},
		{
			id = 42542,
			name = "Stoic Mammoth Hide",
			icon = "Interface\\Icons\\INV_Misc_LeatherScrap_14",
			categories = { 393 },
		},
		{
			id = 2996,
			name = "Bolt of Linen Cloth",
			icon = "Interface\\Icons\\INV_Fabric_Linen_02",
			categories = { 197 },
		},
		{
			id = 4341,
			name = "Yellow Dye",
			icon = "Interface\\Icons\\INV_Potion_12",
			categories = { 197 },
		},
		{
			id = 4589,
			name = "Long Elegant Feather",
			icon = "Interface\\Icons\\Spell_Magic_FeatherFall",
			categories = { 197 },
		},
		{
			id = 6261,
			name = "Orange Dye",
			icon = "Interface\\Icons\\INV_Potion_35",
			categories = { 197 },
		},
		{
			id = 7072,
			name = "Naga Scale",
			icon = "Interface\\Icons\\INV_Misc_MonsterScales_01",
			categories = { 197 },
		},
		{
			id = 9210,
			name = "Ghost Dye",
			icon = "Interface\\Icons\\INV_Poison_MindNumbing",
			categories = { 197 },
		},
		{
			id = 10290,
			name = "Pink Dye",
			icon = "Interface\\Icons\\INV_Potion_09",
			categories = { 197 },
		},
		{
			id = 11040,
			name = "Morrowgrain",
			icon = "Interface\\Icons\\INV_Misc_Herb_05",
			categories = { 197 },
		},
		{
			id = 21842,
			name = "Bolt of Imbued Netherweave",
			icon = "Interface\\Icons\\INV_Fabric_Netherweave_Bolt_Imbued",
			categories = { 197 },
		},
		{
			id = 21845,
			name = "Primal Mooncloth",
			icon = "Interface\\Icons\\INV_Fabric_MoonRag_Primal",
			categories = { 197 },
		},
		{
			id = 21881,
			name = "Netherweb Spider Silk",
			icon = "Interface\\Icons\\Spell_Nature_Web",
			categories = { 197 },
		},
		{
			id = 21882,
			name = "Soul Essence",
			icon = "Interface\\Icons\\Spell_Shadow_SoulLeech_3",
			categories = { 197 },
		},
		{
			id = 38426,
			name = "Eternium Thread",
			icon = "Interface\\Icons\\INV_Misc_Thread_01",
			categories = { 197 },
		},
		{
			id = 41510,
			name = "Bolt of Frostweave",
			icon = "Interface\\Icons\\INV_Fabric_Frostweave_Bolt",
			categories = { 197 },
		},
		{
			id = 41511,
			name = "Bolt of Imbued Frostweave",
			icon = "Interface\\Icons\\INV_Fabric_Frostweave_ImbuedBolt",
			categories = { 197 },
		},
		{
			id = 41593,
			name = "Ebonweave",
			icon = "Interface\\Icons\\INV_Fabric_Ebonweave",
			categories = { 197 },
		},
		{
			id = 41594,
			name = "Moonshroud",
			icon = "Interface\\Icons\\INV_Fabric_Moonshroud",
			categories = { 197 },
		},
		{
			id = 41595,
			name = "Spellweave",
			icon = "Interface\\Icons\\INV_Fabric_Spellweave",
			categories = { 197 },
		},
		{
			id = 42253,
			name = "Iceweb Spider Silk",
			icon = "Interface\\Icons\\INV_Misc_Web_01",
			categories = { 197 },
		},
		{
			id = 4582,
			name = "Soft Bushy Tail",
			icon = "Interface\\Icons\\INV_Misc_MonsterTail_02",
			categories = { 0 },
		},
		{
			id = 5117,
			name = "Vibrant Plume",
			icon = "Interface\\Icons\\INV_Feather_12",
			categories = { 0 },
		},
		{
			id = 5134,
			name = "Small Furry Paw",
			icon = "Interface\\Icons\\Ability_Hunter_MendPet",
			categories = { 0 },
		},
		{
			id = 11018,
			name = "Un'Goro soil",
			icon = "Interface\\Icons\\INV_Misc_Dust_02",
			categories = { 0 },
		},
		{
			id = 11022,
			name = "Packet of Tharlendris Seeds",
			icon = "Interface\\Icons\\Spell_Nature_ProtectionFormNature",
			categories = { 0 },
		},
		{
			id = 11404,
			name = "Evil Bat Eye",
			icon = "Interface\\Icons\\INV_Misc_Eye_01",
			categories = { 0 },
		},
		{
			id = 11407,
			name = "Torn Bear Pelt",
			icon = "Interface\\Icons\\INV_Misc_Pelt_Bear_Ruin_05",
			categories = { 0 },
		},
		{
			id = 11515,
			name = "Corrupted Soul Shard",
			icon = "Interface\\Icons\\INV_Enchant_ShardRadientSmall",
			categories = { 0 },
		},
		{
			id = 11516,
			name = "Cenarion Plant Salve",
			icon = "Interface\\Icons\\INV_Drink_17",
			categories = { 0 },
		},
		{
			id = 12840,
			name = "Minion's Scourgestone",
			icon = "Interface\\Icons\\INV_Jewelry_Talisman_14",
			categories = { 0 },
		},
		{
			id = 12841,
			name = "Invader's Scourgestone",
			icon = "Interface\\Icons\\INV_Jewelry_Talisman_13",
			categories = { 0 },
		},
		{
			id = 12843,
			name = "Corruptor's Scourgestone",
			icon = "Interface\\Icons\\INV_Jewelry_Talisman_12",
			categories = { 0 },
		},
		{
			id = 18944,
			name = "Incendosaur Scale",
			icon = "Interface\\Icons\\INV_Misc_MonsterScales_16",
			categories = { 0 },
		},
		{
			id = 18945,
			name = "Dark Iron Residue",
			icon = "Interface\\Icons\\INV_Enchant_DustSoul",
			categories = { 0 },
		},
		{
			id = 19933,
			name = "Glowing Scorpid Blood",
			icon = "Interface\\Icons\\Spell_Shadow_LifeDrain",
			categories = { 0 },
		},
		{
			id = 21377,
			name = "Deadwood Headdress Feather",
			icon = "Interface\\Icons\\INV_Feather_13",
			categories = { 0 },
		},
		{
			id = 21383,
			name = "Winterfall Spirit Beads",
			icon = "Interface\\Icons\\INV_Jewelry_Amulet_05",
			categories = { 0 },
		},
	},
	]]
}
